### ISSUE TITLE
How to show monthly stats?

### ISSUE THREAD

**Issue by derMart** [eneiluj/cospend-nc#105]
The screenshots in the Readme show this nice monthly stats of projects. Using Cospend 1.4.3 on Nextcloud 22 instance I am sadly unable to find how to display them. Can anyone help?

**Comment by eneiluj** [comment]
Left sidebar (navigation bar) => project item => three dot menu => statistics
Any better?

**Comment by derMart** [comment]
yes, found it, perfect. Thanks!
