### ISSUE TITLE
MYSQL Error 2006 after update to Nextcloud 23

### ISSUE THREAD

**Issue by zagub59** [eneiluj/cospend-nc#106]
Hi !

I just upgraded my Nexcloud system from 21.4 to last version (23.0.0) and I can't get Cospend 1.4.3 to work again. 

Had to disable the app for the upgrade process to complete (via occ in SSH) and now, I can't enable it anymore as I get the following message : _Doctrine\DBAL\Exception\ConnectionLost: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away_

Already tried to delete the app and reinstall it, launch the occ maintenance:repair and mysqlcheck commands without success.

Also tried to add the max_allowed_packet = 512M in /etc/mysql/my.cnf but nothing changed.

I'm running Mariadb 10.5.13 and PHP 8.0.13 on Debian 9.13.

Any help would be greatly appreciated.

Thanks !

**Comment by redpixy** [comment]
I remember seeing in the pre-upgrade warning of nextcloud 23, it isn't compatible with the current version of cospend. You might want to consider using v22.2.3 if you require cospend.

**Comment by zagub59** [comment]
Hi and thank you for your answer !

Tried to rollback to my v21.0.4 snapshot, updated to 21.0.7 and tried cospend : the app's working.

I then updated to v22.2.3 but update failed because of cospend that I had to disable. Tried to enable the app after update successful and got the same error as in v23 : MySQL Error 2006. 

It seems that cospend is not compatible to v22+ :(

**Comment by cestmoimeme** [comment]
Humm ... my nexcloud version is Nextcloud Hub II (23.0.0) nad my cospend version 1.4.3
And it works like a  charm

But my use is may be different from yours : I just create a cospend project when having time with friends, then I cancel it when everyone has his money left . So I can't tell about "old datas and nextcloud migration".

But for my case, it works - My nextcloud is 23 from last sunday, I created a new cospend thurday and i'm still using it .

May be you can try uninstall and re install cospend ?

**Comment by zagub59** [comment]
Hi @cestmoimeme ,

I already tried to delete the app, even remove the files directly in the apps folder by SSH but it did not change anything.

My guess is something went wrong in the database when upgrading from 21 to 23 but I'm not sufficiently expert in SQL to explore this trail any further :(

**Comment by cestmoimeme** [comment]
If you can access sql, I suggestyou to remove the app, then delete the cospend tables then install again.
All cospend tables names begin with oc_cospend..... 

here the cospend tables I have in my nextcloud :
oc_cospend_bill_owers       
oc_cospend_bills            
oc_cospend_categories
oc_cospend_currencies 
oc_cospend_members
oc_cospend_paymentmodes
oc_cospend_projects
oc_cospend_shares 

No need to be an expert in sql. 
Drop table oc_cospend_shares deletes the oc_cospend_shares table

Of course, you will lost all your cospend data by doign that

**Comment by zagub59** [comment]
Issue solved following your instructions and also adding the command DELETE FROM oc_migrations WHERE app = 'cospend' to make rid of the error "There is no table with name 'nextcloud.oc_cospend_shares' in the schema."

I then updated Nextcloud to v23.0.0 and it works like a charm.

Thanks again !

**Comment by eneiluj** [comment]
Triaging. Feel free to reopen if needed.
