### ISSUE TITLE
Undo PT-PT language changes

### ISSUE THREAD

**Issue by LeoColman** [eneiluj/cospend-nc#110]
Hi!
I'm the guy from the Portuguese (Brazilian) PR #109 

I wanted to improve PT-PT in the same fashion, adding some of the remaining strings. I wanted to add the Brazilian string only if the string was untranslated.
I thought that was how Crowdin worked, but I replaced the entirety of the Portuguese (Portugal) translation with the PT-BR translation.

The languages are similar, but if the translation was already made to PT-PT, it should be kept, and not replaced.

I contacted Crowdin to help me fix this, and they told me the maintainer can easily undo a change. Could you do this for me, please? Sorry for the oopsie

**Comment by eneiluj** [comment]
Sorry for the late answer.
Done (well, undone). I could just undo all changes at once. I hope you didn't loose too much translations because of that.
