### ISSUE TITLE
German Umlauts (ä,ö,ü) error in csv export file

### ISSUE THREAD

**Issue by kojid0** [eneiluj/cospend-nc#112]
Steps to reproduce:
1) Create a bill and comment "schönes Abrechnungstool"
2) Go to settings and export the project
3) Open it in Calc/Excel
4) See "sch%C3%B6nes+Abrechnungstool"

Additionally to this, consider replacing "+" with a blank/space or "_" for better readability

**Comment by kojid0** [comment]
Also "," is "%2C"

**Comment by eneiluj** [comment]
As comments can contain new lines (`\n`), when exporting a project, they are encoded with Php's `urlencode` function. They are decoded on import.

Why do you open exported projects in a spreadsheet editor?
Those files are meant to be imported back to Cospend or any other compatible system. They can also be processed for stats or whatever you want.
But they are not meant to be human readable :grin:.

**Comment by kojid0** [comment]
Makes sense.

> Why do you open exported projects in a spreadsheet editor? 

I just saw it when I wanted to print out the whole project in order to hand it out to a friend, but it doesn't need to be fixed. I have other suggestion I will share with you soon.
