### ISSUE TITLE
The weight no longer works ...

### ISSUE THREAD

**Issue by cestmoimeme** [eneiluj/cospend-nc#115]
HI there
Me again for a problem I didn't have before.
My cospend version is 1.4.3
My nextlcoud 23.0.0

On the picture you can see the amount is not ok ... 

Thank you to look at it :)

hum ... no ... I guess it's ok ... 
oups , sorry

**Comment by cestmoimeme** [comment]
[](url)
<img width="1227" alt="Capture d’écran 2022-01-15 à 13 05 59" src="https://user-images.githubusercontent.com/17205394/149623325-dbc6873a-d6ee-4228-9ea2-23902d2de72c.png">

**Comment by cestmoimeme** [comment]
![Uploading Capture d’écran 2022-01-15 à 14.27.26.png…]()

**Comment by cestmoimeme** [comment]
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/17205394/149623410-18c28695-2e90-4655-ad9a-40a368423ac2.png">

**Comment by cestmoimeme** [comment]
That means that cospend is really useful because doing these calculations "by hand" is headache! 
Thanks for this app!

**Comment by eneiluj** [comment]
:grin: Alright then.
