### ISSUE TITLE
How to completely remove cospend (from database)

### ISSUE THREAD

**Issue by paskalito** [eneiluj/cospend-nc#119]
When i Try to install Cospend i get the following error:

Error: There is no table with name 'nextcloud.oc_cospend_categories' in the schema.

it looks like illustrated here : https://github.com/nextcloud/bookmarks/issues/1719

i guess it is possible that there are traces from an old install on my instance. and now it breaks.

is there any list of which tables i would need to delete for a comlete reinstall as in:
https://github.com/nextcloud/bookmarks/wiki/Removing-all-traces-from-DB

(remove and install does not help)

**Comment by paskalito** [comment]
is this https://github.com/eneiluj/cospend-nc/issues/106#issuecomment-991942895 a complete list of the Databases that there have might been?

So that this

`drop table oc_cospend_bill_owers; drop table oc_cospend_bills; drop table oc_cospend_categories; drop table oc_cospend_currencies; drop table oc_cospend_members; drop table oc_cospend_paymentmodes; drop table oc_cospend_projects; drop table oc_cospend_shares; delete from oc_migrations where app = 'cospend';`

Would be a complete SQL Command. (I have close so zero SQL knowledge)

Also [this Comment](https://github.com/eneiluj/cospend-nc/issues/106#issuecomment-991962174) seems to imply that ` delete from oc_migrations where app = 'cospend';` would maybe me enough.

Or is it even, that i should just create 'nextcloud.oc_cospend_categories' - or would that break stuff ? ( i then still could delete everything anyway..)

**Comment by paskalito** [comment]
hmm i looked around in the code, and concluded. it is a bit more complicated. so i let go the plan of creating a new table.
after querying my database i also think more tables are missing anyway.

when i just `delete from oc_migrations where app = 'cospend';` i get `Error: The column 'autoexport' on table 'oc_cospend_projects' already exists.`

then i ran this on the db container
` mysql -u nextcloud -D nextcloud -ppassword -e "show tables" -s | egrep "^oc_cospend_" | xargs -I "@@" echo mysql -u nextcloud -D nextcloud -ppassword -e "DROP TABLE @@"`

and checked if this was sensible output.
and followed with this georgous all in one deinstall command [explained here](https://stackoverflow.com/questions/456751/drop-mysql-databases-matching-some-wildcard)
` mysql -u nextcloud -D nextcloud -ppassword -e "show tables" -s | egrep "^oc_cospend_" | xargs -I "@@" mysql -u nextcloud -D nextcloud -ppassword -e "DROP TABLE @@" && mysql -u nextcloud -D nextcloud -ppassword -e "delete from oc_migrations where app = 'cospend';"`

then i tried to install and got an "cospend already installed" message.
then i removed and installed again.
Now everything works.

**Comment by yeupou** [comment]
In my case, the problem is still happening and even though the install seems to be working after running

mysql -u oc_root -D nextcloud -pPASS -e "show tables" -s | egrep "^oc_cospend_" | xargs -I "@@" mysql -u oc_root -D nextcloud -pPASS -e "DROP TABLE @@" && mysql -u oc_root -D nextcloud -pPASS -e "delete from oc_migrations where app = 'cospend';"

It shows
![image](https://user-images.githubusercontent.com/1160681/170542282-7bda4828-20df-4bd5-8997-c8a5f95d8fb2.png)

**Comment by eneiluj** [comment]
@yeupou Could you give us more information about what you did exactly?

My advice is to:
* disable Cospend
* delete the oc_cospend_* tables and the entries in oc_migrations
* check there is no more table with a name beginning with oc_cospend
* enable Cospend

The server log might help (or just the relevant lines) as it will show the actual error stack trace. You can that by adapting this command with your context:
```
grep -i cospend /.../nextcloud/data/nextcloud.log > cospend.log
```
