### ISSUE TITLE
Bug: Not showing anything on mobile

### ISSUE THREAD

**Issue by brunothg** [eneiluj/cospend-nc#126]
Cospend is showing nothing on mobile devices. Desktop browser are not affected.
Can be emulated with device emulation of desktop browsers (tested with Edge and Chrome on Windows eg. Pixel 5).

HTML main element (id="app-content-vue" class="app-content no-snapper") stays empty after loading cospend app.

Nextcloud version: 22.2.5
Cospend version: 1.4.5, 1.4.4 (1.4.3 is fine)
Browser: Chrome, Edge, Firefox (all mobile and emulated)

**Comment by rriemann** [comment]
Same problem here!

**Comment by tiritibambix** [comment]
Same problem here.

**Comment by eneiluj** [comment]
Thanks for the bug report. I found the problem thanks to `git bisect` but have no clue why using the new Vue slot syntax has this effect...

Anyway, v1.4.6-1-nightly is out. Could someone try it and confirm it's working fine now?
A small guide to install the nightly: https://github.com/eneiluj/cospend-nc#nightly

**Comment by tiritibambix** [comment]
> Thanks for the bug report. I found the problem thanks to `git bisect` but have no clue why using the new Vue slot syntax has this effect...
> 
> Anyway, v1.4.6-1-nightly is out. Could someone try it and confirm it's working fine now? A small guide to install the nightly: https://github.com/eneiluj/cospend-nc#nightly

That's great news.
Unfortunately, I'm afh for a couple weeks and won't be able to test nightly for now.

**Comment by cestmoimeme** [comment]
I tried it and it's ok for me on a iphone (but to say the truth, I didn't notice the problem cause I do not use cospend these days :) I just made a test by now )

**Comment by brunothg** [comment]
I can confirm it.
On my test system the 1.4.6-1-nightly is working fine with device emulation (edge, firefox and chrome).

**Comment by eneiluj** [comment]
@cestmoimeme @brunothg Thanks a lot for the feedback :heart: 
@tiritibambix Feel free to reopen if something is wrong with v1.4.6 (which is coming soon).

**Comment by tiritibambix** [comment]
> @cestmoimeme @brunothg Thanks a lot for the feedback ❤️ @tiritibambix Feel free to reopen if something is wrong with v1.4.6 (which is coming soon).

Thanks a lot :)
