### ISSUE TITLE
[PHP] Error: Trying to access array offset on value of type null at /usr/local/www/nextcloud/apps/cospend/lib/Controller/PageController.php#1314

### ISSUE THREAD

**Issue by rm76** [eneiluj/cospend-nc#127]
Hi!
Please bear in mind that I'm not a programmer so I don't know what to make of this PHP error that shows up in my Nextcloud log, other than reporting it to you.
I'm running Cospend 1.4.5 in Nextcloud Hub II 23.0.2 in a TrueNAS (FreeBSD) jail.
The database is MariaDB 10.5.15.
That error occurred when accessing cospend with Android app MoneyBuster 0.1.16.

Formatted:
```
[PHP] Error: Trying to access array offset on value of type null at /usr/local/www/nextcloud/apps/cospend/lib/Controller/PageController.php#1314

POST /index.php/apps/cospend/api/projects/1/loppe/bills
from 10.0.1.2 at 2022-03-15T20:57:36+01:00
```

Raw:
`
{"reqId":"BAyt1O4ngWIfREpLgzNa","level":3,"time":"2022-03-15T20:57:36+01:00","remoteAddr":"10.0.1.2","user":"--","app":"PHP","method":"POST","url":"/index.php/apps/cospend/api/projects/1/loppe/bills","message":"Trying to access array offset on value of type null at /usr/local/www/nextcloud/apps/cospend/lib/Controller/PageController.php#1314","userAgent":"MoneyBuster/0.1.16","version":"23.0.2.1","exception":{"Exception":"Error","Message":"Trying to access array offset on value of type null at /usr/local/www/nextcloud/apps/cospend/lib/Controller/PageController.php#1314","Code":0,"Trace":[{"file":"/usr/local/www/nextcloud/apps/cospend/lib/Controller/PageController.php","line":1314,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"apiAddBill","class":"OCA\\Cospend\\Controller\\PageController","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/local/www/nextcloud/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/local/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/usr/local/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"62319cc9409c4"}
`

**Comment by eneiluj** [comment]
Thanks a lot for reporting this :heart: . Same mistake for bill edition API endpoint. Both are fixed now. This will be included in v1.4.6 which is coming soon.
