### ISSUE TITLE
Bug: Navigation button icon missing

### ISSUE THREAD

**Issue by brunothg** [eneiluj/cospend-nc#129]
Cospend is missing the icon for the navigation button for mobile devices (see screenshot).
Can be emulated with device emulation of desktop browsers (tested with Edge and Chrome on Windows eg. Pixel 5).

![screenshot](https://user-images.githubusercontent.com/6464629/161449212-459200db-cf32-415a-b3fc-bf73a6106d03.jpg)

Nextcloud version: 22.2.6, 23.0.3
Cospend version: 1.4.6
Browser: Chrome, Edge, Firefox (all mobile and emulated)

**Comment by eneiluj** [comment]
Hi, thanks for the issue. This seems to be resolved by upgrading the `@nextcloud/vue` package to v5.3.0. The fix will be included in the next release.
