### ISSUE TITLE
Deleting/creating a bill does not update the amounts in the menu

### ISSUE THREAD

**Issue by nicofrand** [eneiluj/cospend-nc#134]
Hi,

thanks for this nice tool!

When creating a bill through the autosettlement feature, the amounts in the menu bar, per user, are not updated unless I reload the page.
When deleting a bill (generated automatically with the auto-settlement feature), the amounts in the menu bar, per user, are not updated unless I reload the page.

See on screenshot: a settlement bill was created for Marion with an amount on 20.16 but the menu still shows that Marion still owes 20€16.

![Screenshot_20220428_103110](https://user-images.githubusercontent.com/3419050/165711663-77cd8e78-3c22-4460-86dc-053d90f31e18.png)

**Comment by eneiluj** [comment]
Hi, thanks for the issue.

I can't reproduce on the master branch. Balances are updated on auto settlement, bill creation and bill deletion.
Which Cospend version are you using?

Do you see any error in the browser console (F12 -> console tab)?

**Comment by nicofrand** [comment]
Thank you for your quick reply!

I am using version 1.4.6 (installed through Nextcloud's web admin).

Nothing in the browser console, the bill deletion works fine according to the server (Response to DELETE request = `OK`).

That's weird though, I am unable to reproduce when the devtools are enabled (and cache is disabled) so that might be a cache issue.

When a bill is deleted, how are the sums updated? Are they updated instantly or after a HTTP request (ie. could a broken cache cause the issue?).?

**Comment by nicofrand** [comment]
OK sorry, it took me a while to understand, it comes from my environment (I installed Nextcloud through YunoHost) and is most probably a cache issue: https://github.com/YunoHost-Apps/nextcloud_ynh/issues/484.

Sorry for the time taken and thanks again for the app!
