### ISSUE TITLE
Error creating new Projects. ERROR: double keyvalues

### ISSUE THREAD

**Issue by heimchemiker** [eneiluj/cospend-nc#142]
Hi all,
When I try to create a new Project in Cospend in my Nextcloud instance, it throws an error saying:

> Neues Projekt konnte nicht erstellt werden
translate: "New project could not be created"

upon reloading the page, the Project is created, but the error protocol says:

>  [index] Fehler: An exception occurred while executing a query: SQLSTATE[23505]: Unique violation: 7 FEHLER:  doppelter Schlüsselwert verletzt Unique-Constraint »oc_cospend_categories_pkey«
> DETAIL:  Schlüssel »(id)=(24)« existiert bereits.
> 
> POST /apps/cospend/projects
> from xxx.xxx.xxx.xxx by Steve at 2022-05-11T11:15:30+02:00
translate: Error: double keyvalue violates Unique-constraint »oc_cospend_categories_pkey«      DETAIL: key  »(id)=(24)« already exists.

My Nexcloud (22.0.3) instance runs on a VM with Ubuntu 20.04, a Nginx (1.21.6) webserver/reverse proxy, php 8.0.18 and a PostgreSQL (13.6) database.

How do I solve this problem?

<details>
  <summary> Complete Error from the nextcloud protocol: </summary>

OC\DB\Exceptions\DbalException: An exception occurred while executing a query: SQLSTATE[23505]: Unique violation: 7 FEHLER: doppelter Schlüsselwert verletzt Unique-Constraint »oc_cospend_categories_pkey« DETAIL: Schlüssel »(id)=(24)« existiert bereits

0. /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 335:
   OC\DB\Exceptions\DbalException::wrap()
1. /var/www/nextcloud/apps/cospend/lib/Service/ProjectService.php - line 534:
   OC\DB\QueryBuilder\QueryBuilder->executeStatement()
2. /var/www/nextcloud/apps/cospend/lib/Controller/PageController.php - line 425:
   OCA\Cospend\Service\ProjectService->createProject()
3. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:
   OCA\Cospend\Controller\PageController->webCreateProject()
4. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:
   OC\AppFramework\Http\Dispatcher->executeController()
5. /var/www/nextcloud/lib/private/AppFramework/App.php - line 157:
   OC\AppFramework\Http\Dispatcher->dispatch()
6. /var/www/nextcloud/lib/private/Route/Router.php - line 302:
   OC\AppFramework\App::main()
7. /var/www/nextcloud/lib/base.php - line 1008:
   OC\Route\Router->match()
8. /var/www/nextcloud/index.php - line 36:
   OC::handleRequest()

Verursacht durch Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing a query: SQLSTATE[23505]: Unique violation: 7 FEHLER: doppelter Schlüsselwert verletzt Unique-Constraint »oc_cospend_categories_pkey« DETAIL: Schlüssel »(id)=(24)« existiert bereits.

0. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php - line 1780:
   Doctrine\DBAL\Driver\API\PostgreSQL\ExceptionConverter->convert()
1. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php - line 1719:
   Doctrine\DBAL\Connection->handleDriverException()
2. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php - line 1173:
   Doctrine\DBAL\Connection->convertExceptionDuringQuery()
3. /var/www/nextcloud/lib/private/DB/Connection.php - line 270:
   Doctrine\DBAL\Connection->executeStatement()
4. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php - line 354:
   OC\DB\Connection->executeStatement()
5. /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 287:
   Doctrine\DBAL\Query\QueryBuilder->execute()
6. /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 333:
   OC\DB\QueryBuilder\QueryBuilder->execute()
7. /var/www/nextcloud/apps/cospend/lib/Service/ProjectService.php - line 534:
   OC\DB\QueryBuilder\QueryBuilder->executeStatement()
8. /var/www/nextcloud/apps/cospend/lib/Controller/PageController.php - line 425:
   OCA\Cospend\Service\ProjectService->createProject()
9. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:
   OCA\Cospend\Controller\PageController->webCreateProject()
10. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:
   OC\AppFramework\Http\Dispatcher->executeController()
11. /var/www/nextcloud/lib/private/AppFramework/App.php - line 157:
   OC\AppFramework\Http\Dispatcher->dispatch()
12. /var/www/nextcloud/lib/private/Route/Router.php - line 302:
   OC\AppFramework\App::main()
13. /var/www/nextcloud/lib/base.php - line 1008:
   OC\Route\Router->match()
14. /var/www/nextcloud/index.php - line 36:
   OC::handleRequest()

Verursacht durch Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[23505]: Unique violation: 7 FEHLER: doppelter Schlüsselwert verletzt Unique-Constraint »oc_cospend_categories_pkey« DETAIL: Schlüssel »(id)=(24)« existiert bereits.

0. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php - line 94:
   Doctrine\DBAL\Driver\PDO\Exception::new()
1. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php - line 1163:
   Doctrine\DBAL\Driver\PDO\Statement->execute()
2. /var/www/nextcloud/lib/private/DB/Connection.php - line 270:
   Doctrine\DBAL\Connection->executeStatement()
3. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php - line 354:
   OC\DB\Connection->executeStatement()
4. /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 287:
   Doctrine\DBAL\Query\QueryBuilder->execute()
5. /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 333:
   OC\DB\QueryBuilder\QueryBuilder->execute()
6. /var/www/nextcloud/apps/cospend/lib/Service/ProjectService.php - line 534:
   OC\DB\QueryBuilder\QueryBuilder->executeStatement()
7. /var/www/nextcloud/apps/cospend/lib/Controller/PageController.php - line 425:
   OCA\Cospend\Service\ProjectService->createProject()
8. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:
   OCA\Cospend\Controller\PageController->webCreateProject()
9. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:
   OC\AppFramework\Http\Dispatcher->executeController()
10. /var/www/nextcloud/lib/private/AppFramework/App.php - line 157:
   OC\AppFramework\Http\Dispatcher->dispatch()
11. /var/www/nextcloud/lib/private/Route/Router.php - line 302:
   OC\AppFramework\App::main()
12. /var/www/nextcloud/lib/base.php - line 1008:
   OC\Route\Router->match()
13. /var/www/nextcloud/index.php - line 36:
   OC::handleRequest()

Verursacht durch PDOException: SQLSTATE[23505]: Unique violation: 7 FEHLER: doppelter Schlüsselwert verletzt Unique-Constraint »oc_cospend_categories_pkey« DETAIL: Schlüssel »(id)=(24)« existiert bereits.

0. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php - line 92:
   PDOStatement->execute()
1. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php - line 1163:
   Doctrine\DBAL\Driver\PDO\Statement->execute()
2. /var/www/nextcloud/lib/private/DB/Connection.php - line 270:
   Doctrine\DBAL\Connection->executeStatement()
3. /var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php - line 354:
   OC\DB\Connection->executeStatement()
4. /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 287:
   Doctrine\DBAL\Query\QueryBuilder->execute()
5. /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 333:
   OC\DB\QueryBuilder\QueryBuilder->execute()
6. /var/www/nextcloud/apps/cospend/lib/Service/ProjectService.php - line 534:
   OC\DB\QueryBuilder\QueryBuilder->executeStatement()
7. /var/www/nextcloud/apps/cospend/lib/Controller/PageController.php - line 425:
   OCA\Cospend\Service\ProjectService->createProject()
8. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:
   OCA\Cospend\Controller\PageController->webCreateProject()
9. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:
   OC\AppFramework\Http\Dispatcher->executeController()
10. /var/www/nextcloud/lib/private/AppFramework/App.php - line 157:
   OC\AppFramework\Http\Dispatcher->dispatch()
11. /var/www/nextcloud/lib/private/Route/Router.php - line 302:
   OC\AppFramework\App::main()
12. /var/www/nextcloud/lib/base.php - line 1008:
   OC\Route\Router->match()
13. /var/www/nextcloud/index.php - line 36:
   OC::handleRequest()

</details>

**Comment by eneiluj** [comment]
I assume you're using Cospend v1.4.6, right?

Something is messed up with the auto increment for the "id" column of the oc_cospend_categories. Have you made any manual changes to the database?

Project creation works in the CI tests with PostgreSQL. I can't think of any reason why this would happen.

**Comment by eneiluj** [comment]
I'm interested to know if 1. worked and if not, if 2. worked :grin:.

**Comment by heimchemiker** [comment]
Emptying the table (suggestion number 1) worked.
So far it does not throw another error.
Thank you very much for the help.

**Comment by lkempf** [comment]
I also got a very similar error and I didn't touch my database (also postgres) in the last couple of months.

```
An exception occurred while executing a query: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "oc_cospend_categories_pkey" DETAIL: Key (id)=(15) already exists.
```

Maybe I can help investigate this the next couple of days. 
I have database backups going back a couple of weeks/months.

**Comment by lkempf** [comment]
Ok I still don't know why that happened but I found a proper fix since I had important data in cospend. The id sequences for `oc_cospend_categories` and `oc_cospend_paymentmodes` got reset somehow and needed to be set to a working value.
This can be done by running
```
SELECT setval('oc_cospend_categories_id_seq', COALESCE((SELECT MAX(id)+1 FROM oc_cospend_categories), 1), false);
SELECT setval('oc_cospend_paymentmodes_id_seq', COALESCE((SELECT MAX(id)+1 FROM oc_cospend_paymentmodes), 1), false);
```

**Comment by rexkani** [comment]
> Ok I still don't know why that happened but I found a proper fix since I had important data in cospend. The id sequences for `oc_cospend_categories` and `oc_cospend_paymentmodes` got reset somehow and needed to be set to a working value. This can be done by running
> 
> ```
> SELECT setval('oc_cospend_categories_id_seq', COALESCE((SELECT MAX(id)+1 FROM oc_cospend_categories), 1), false);
> SELECT setval('oc_cospend_paymentmodes_id_seq', COALESCE((SELECT MAX(id)+1 FROM oc_cospend_paymentmodes), 1), false);
> ```

i had the same issue and this is a VERY important fix for people like us!
