### ISSUE TITLE
Project title color barely visible with light background colors

### ISSUE THREAD

**Issue by Ezwen** [eneiluj/cospend-nc#160]
I'm using Cospend on a Nextcloud instance where the appearance has been customized − in particular, the background color for the whole instance is a very light grey (#F5F5F5).

This leads to problems with Cospend, as can be seen in my projects left panel:
![image](https://user-images.githubusercontent.com/1388961/179397009-80d0215d-2bc7-49a8-8b6e-3b44e03bbb72.png)

Just below the "Nouveau projet" label (_New project_ in French) appears the single project I have in my Cospend space. It is barely visible because the text label is written in white above the very light gray background.

**Comment by eneiluj** [comment]
Thanks for reporting this issue. It's now fixed and available in the latest nightly release (if you want to try it). It will be included in the next release.

Feel free to report any other color issue when the theming color is very light.

**Comment by Ezwen** [comment]
Very cool, thank you very much for the prompt fix! I'll let you know if there is any problem.
