### ISSUE TITLE
Clicking on a project name should always show all bills

### ISSUE THREAD

**Issue by siccovansas** [eneiluj/cospend-nc#168]
If you click on a project (which isn't currently selected) you are shown all bills of that project. If you then click on a member then you see the bills of that member. If you then click again on the project, nothing happens. I would expect to see all the bills again. Currently you need to again click on the member to 'deselect' it in order to show all bills of the project. To me this wasn't intuitive and I only figured this out by accident (before that, I used to click on another project and then again on the project I was viewing to show all bills of that project).

It is fine to keep the 'deselect member' behavior, but it would be great if clicking the project always shows the list of all bills :)!

Thanks for this great app!

**Comment by eneiluj** [comment]
Nice idea. Done and available in v1.4.9-6-nightly. It would be nice if you could try it before the next release. You can also wait for the next release.
