### ISSUE TITLE
Issue : Bills disappeared

### ISSUE THREAD

**Issue by xetyr** [eneiluj/cospend-nc#17]
Hey there,

First, I want to express a big thanks to coders of this add-on. It's quite simple, but very helpful ! As you said : "Sometimes small tools save big time"

Unfortunately, I've a trouble with an existing project. All my bills disappeared but the balance is still present. I think this bug appeared when I updated PHP7.4 to the last version. Could it be possible ?

How to repair it ?

**Comment by eneiluj** [comment]
Hi,

If the balances are ok, the bills must still be there. I think they are just not displayed. Let's find out why.

* Which Cospend version are you using?
* Is it happening to all your projects?
* Is there an error in the javascript console (F12 => Console tab) when loading the page?
* What is your browser (and version)?
* Are there errors in Nextcloud's server logs? (`/var/www/html/nextcloud/data/nextcloud.log` or something like that)
* Which Php version are you using now?

I don't see how a more recent Php version could be problematic.

Thanks for the bug report.

**Comment by xetyr** [comment]
Hey,

• Cospend v1.2.0
• I've only one project, but 
• I use Brave browser but I also tried with Opera, same issue
• Yes, I can see a lot of errors in the javascript console, but I'm not sure which one is related to Cospend

> TypeError: Cannot read property 'cacheBuster' of undefined
>     at a.data (Sidebar.vue:112)
>     at vue.runtime.esm.js:4748
>     at vue.runtime.esm.js:4705
>     at vue.runtime.esm.js:4642
>     at a.e._init (vue.runtime.esm.js:5006)
>     at new a (vue.runtime.esm.js:5154)
>     at vue.runtime.esm.js:3283
>     at init (vue.runtime.esm.js:3114)
>     at vue.runtime.esm.js:5978
>     at m (vue.runtime.esm.js:5925)

• PHP 7.4.12
• Nextcloud log also registered some errors, but several are related to the upgrade to Nextcloud 20 (still beta)

How can I furnish more relevant information ?

**Comment by eneiluj** [comment]
> I'm not sure which one is related to Cospend

The one you mentioned is related to Cospend :grin:. It appears you don't have the theming app enabled or something else is preventing `window.OCA.Theming.cacheBuster` to exist. It's fixed now. It will be available in next release coming soon.

Thanks a lot

**Comment by eneiluj** [comment]
v1.2.1 is out. I'm interested to know if it solved your issue.

**Comment by xetyr** [comment]
> v1.2.1 is out. I'm interested to know if it solved your issue.

It definitively solved the issue !

Thank's a lot 👍 🥇

**Comment by eneiluj** [comment]
Thanks a lot for the feedback! Glad it works now.
