### ISSUE TITLE
Can't load statistics

### ISSUE THREAD

**Issue by rubikonx9** [eneiluj/cospend-nc#171]
Issue:
When I click on Project's `...` -> `Statistics`, the page doesn't display the statistics.
Part of the layout is rendered (horizontal bars and spinners), but no data is displayed afterwards.
It used to work in the past, but I am not able to tell in which exact version it went bad.

Nextcloud: 24.0.4
Cospend: 1.4.8
Nextcloud's database: mariadb 10.9.2

Browsers:
Firefox 103.0.2
Chrome 105.0.5195.10

JavaScript console contains error, but they're different depending on the browser.
Firefox:

> TypeError: this.stats.monthlyStats is undefined
>    monthlyMemberChartData Statistics.vue:474
>    VueJS 3
>    _e Statistics.vue:5
>    VueJS 7
>    VueJS 10
> [vue.runtime.esm.js:1888:4](webpack://cospend/node_modules/vue/dist/vue.runtime.esm.js)

Chrome:
> vue.runtime.esm.js:1888 TypeError: Cannot read properties of undefined (reading '2022-04')
>    at o.monthlyMemberChartData (Statistics.vue:475:1)
>    at pn.get (vue.runtime.esm.js:4479:25)
>    at pn.evaluate (vue.runtime.esm.js:4584:21)
>    at o.monthlyMemberChartData (vue.runtime.esm.js:4836:17)
>    at o.<anonymous> (Statistics.vue?a7c6:5:1507)
>    at e._render (vue.runtime.esm.js:3548:22)
>    at o.r (vue.runtime.esm.js:4066:21)
>    at pn.get (vue.runtime.esm.js:4479:25)
>    at pn.run (vue.runtime.esm.js:4554:22)
>    at An (vue.runtime.esm.js:4310:13)

**Comment by eneiluj** [comment]
Thanks for reporting this. I can't reproduce the issue with v1.4.8 in my environment. It might be possible to reproduce with your project. Would you export it and share it with me? You can use my email address if you want to avoid sharing the project here.

**Comment by eneiluj** [comment]
Weird thing is that I can't find "monthlyMemberChartData" or "this.stats.monthlyStats" anywhere in the sources of v1.4.8.

Could you reload the page with CTRL+F5 to make sure you don't load a cached version of the javascript files?

**Comment by eneiluj** [comment]
I see that "monthlyMemberChartData" was removed in ddb62e856d435b4718c376d242e489d79766701e (more than a year ago). Any release >= v1.3.10 does not include it anymore.

**Comment by rubikonx9** [comment]
Oh my! This was a good clue.
The fault was on the side of my setup.

When upgrading to Nextcloud v21, because of some changes with permissions, I created a secondary apps directory, so now I have two entries in `apps_paths` var in `config.php`.
And I have two separate copies of `cospend` in both of them - one is the 1.4.8, which is reported in GUI administration and `occ`, and 1.2.9, which wasn't "tracked" properly, but was apparently loaded when navigating the GUI...

I removed the latter one and it works just fine.
I am not sure how this works, but I imagine that initially, when I had only a single `apps` dir, Cospend was installed there; then, when I added seconds `apps` dir, an update of Cospend landed in the new dir, but the old one wasn't removed.

I wonder how many other apps have this problem. I will try to search Nextcloud issues for this.

**Comment by eneiluj** [comment]
Alright thanks for the quick feedback and for the compliment!

**Comment by rubikonx9** [comment]
I opened an issue in Nextcloud repo: https://github.com/nextcloud/server/issues/33794
This is, in fact, a known issue, but I made some suggestions there nonetheless... We'll see.

**Comment by eneiluj** [comment]
Nice, thank you for the effort.
