### ISSUE TITLE
is there any way to have the project DB storage encrypted?

### ISSUE THREAD

**Issue by mortee** [eneiluj/cospend-nc#173]
There may be financial info so sensitive that it should be protected even against physical access to the server's disk. Is there any way to have the info encrypted?

**Comment by Almamu** [comment]
I guess encrypting the disk where the database is stored would be the best approach here.  Although that wouldn't protect you against any malware that gets to run in your server...

**Comment by Almamu** [comment]
Sorry, looks like I closed it without realising, reopen just in case!

**Comment by mortee** [comment]
OK, I see. Well, if encrypted DB is definitely not the scope of this app (like it is of e.g. some self-hosted investment tracking apps), then I just will have to keep my sensitive info somewhere else.
