### ISSUE TITLE
Enhancement: new 'Repeat' payment frequencies

### ISSUE THREAD

**Issue by DrMantisTobbogan** [eneiluj/cospend-nc#19]
It would be great to have two new _Repeat_ payment options:

- Bi-Weekly = every two weeks (monthly payment x 12 divided by 24)
- Semi-Monthly = two payments per month for a total of 24 for the year

Would be useful for recurring mortgage and tax payments. More description of the types can be found [here](http://www.mortgagewisefinancial.com/mortgage-information/mortgage-payment-frequency).

**Comment by eneiluj** [comment]
Hey there. It's been added and is available in v1.2.3-nightly. You can install it manually or wait for the next release that should come soon. It would be nice to have some tests and feedback before releasing :grin:.

* Bi-weekly is basic: repeat every 14 days.
* Semi-monthly is done on 1st and 15th. So if a bill on the 18th is set to 'semi-monthly' repetition, next occurrence will be on 1st of next month, then 15th, then 1st and so on.

**Comment by DrMantisTobbogan** [comment]
Thanks for getting this feature added in, your work on the project is appreciated! 

I manually installed the nightly build and everything looks good so far.  I guess one small improvement could be to customize the semi-monthly days but the 1 and 15th is more then sufficient (and beggars can't be choosers 🤣).

**Comment by eneiluj** [comment]
Thanks for the feedback and the enthusiasm!

Well a lazy way to make it possible to choose semi-monthly days would be to add a global setting but it would probably not reflect the common use case. I guess users want to set those days for each specific bill. This would mean add new stuff in bill edition form and extend the database bill table. I'm not opposed to that but I don't think I will make it soon. I'm very open to pull requests if you want to practice Php and Vue.js :wink:.

Btw, did you know there is an occ command to manually trigger bills repetition (and avoid waiting for the background to run)?
Feel free to reopen if you face problems with those changes.
To be continued. Thanks again for the suggestion.
