### ISSUE TITLE
Readme.md section installation broken link

### ISSUE THREAD

**Issue by mMuck** [eneiluj/cospend-nc#23]
AdminDocs link don't work. Is there a working wiki?
Thanks 🙂

**Comment by eneiluj** [comment]
Links has been fixed in the README and the app description. Thanks for the issue.

There is not much in the admin doc. Were you looking for a specific information?

**Comment by mMuck** [comment]
> Links has been fixed in the README and the app description. Thanks for the issue.

Thanks 👍 

> There is not much in the admin doc. Were you looking for a specific information?

Ahm, yes. I installed the app at my NC instance to test it and opened it first on my mobile firefox browser (68.8.0esr). The main content doesn't show up. This applies to the normal app view (logged in) and the shared link view. All other apps work normal.
I first thought there is an installation step missing but it's a one-click-install-app 👍.

Installed it on an external instance (https://ncdebug.demo.cloudron.io/apps/cospend, admin, changeme; nice tool BTW, will delete itself in some hours) to check if is my installation. It's not. Same error:
![grafik](https://user-images.githubusercontent.com/8143240/102125665-08a37780-3e18-11eb-8477-f15fca5e5ae8.png)
Stays empty. On the desktop browser works normal. Tried another webview-based mobile browser - there it works too. How can I contribute debug information?
This is definitely a different issue, so you can close this one. I can open another, if this remains on the newest FF mobile - I don't like it so I keep my v68.

**Comment by eneiluj** [comment]
It's fine to stay here to discuss the second issue.

It rings a bell. The [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#Browser_compatibility) is used in Cospend and it's supported by FF >= 74.
As FF 68 is more than a year old, I'm kind of ok not to support it, sorry :grin:. I'm sure you can find FF 74 for mobile, it does not have the newest interface.

**Comment by eneiluj** [comment]
Feel free to reopen if needed.
