### ISSUE TITLE
Add missing primary keys

### ISSUE THREAD

**Issue by acsfer** [eneiluj/cospend-nc#24]
As I'm running a MariaDB cluster, migrate to 20.0.2 was expected to fix some (Galera) clustering issues with primary keys on tables. Perhaps, some tables still missing primary keys.

## Steps to reproduce
1. Run `occ db:add-missing-primary-keys`

### Expected behavior
All missing primary keys should be added

### Actual behavior
Following tables don't have primary key:
```
oc_cospend_projects
```
Upgrade from 19.0.5 to 20.0.2

**Comment by eneiluj** [comment]
Thanks a lot. This primary key is missing since...the beginning :sweat:. It's been added. The new DB migration step will be in v1.2.3 which is coming soon.
