### ISSUE TITLE
Feature: Order Categories

### ISSUE THREAD

**Issue by itatabitovski** [eneiluj/cospend-nc#26]
It would be great if Categories in the dropdown are ordered by name or by last recently used.

**Comment by eneiluj** [comment]
Thanks for the suggestion.

Categories order can now be customized by drag'n'drop. IMHO, in most cases it is more convenient to have the most used categories first rather than the recently used ones. What do you think?

This is available in latest nightly build if you want to try/test it. You can also wait for next release.

**Comment by itatabitovski** [comment]
> Thanks for the suggestion.
> 
> Categories order can now be customized by drag'n'drop. IMHO, in most cases it is more convenient to have the most used categories first rather than the recently used ones. What do you think?

I think that alphabetical ordering should be done by default. That Is the most natural and requires little effort to understand. In addition to that there can be other ordering options like:
- recently used categories
- weighted/most used categories
- manually ordered categories

**Comment by eneiluj** [comment]
I agree it would be nice. I started to implement that. For the moment, only alphabetical and manual options are available.
It's available in latest nightly build if you want to try it.

Recent and most used would require much more development. I might do it some day. I'm open to PRs.

**Comment by eneiluj** [comment]
Hey there, "most used" and "most recently used" category sort orders are now available.
This order is now respected everywhere:
* in stats charts
* in stats tables
* in all category selectors

It would be nice if you (or anyone else) could try it. It's available in v1.3.9-1-nightly (which is only compatible with NC 22).
You can easily get it with an occ command (adapt to your context):
```
sudo -u www-data php ./occ app:update --allow-unstable cospend
```
To get back to stable release, just get to the app settings, disable, delete and "download and install" the app.

**Comment by itatabitovski** [comment]
I noticed an unexpected behavior. With the categories ordeding set to Alphabetic, the categories in the dropdown menu in New bill are shuffled.

I've tested with NC 22 and the cospend version as advised above.

**Comment by eneiluj** [comment]
Thanks for the feedback! Yeah I fixed that a few commits after the nightly. It was actually also affecting existing bill edition form.

`v1.3.10-1-nightly` is out and includes the fix. Could you try it?

**Comment by itatabitovski** [comment]
It works as expected now :+1:
