### ISSUE TITLE
projectname written in camelcase throws "Unauthorized action" while using API

### ISSUE THREAD

**Issue by stanislavhannes** [eneiluj/cospend-nc#35]
Hey, 
I am developing an app that uses the API from your application.
I had an project called "wgWalltor" and tried to get the members of the project.
But couldn't until I changed the name to "wgwalltor". 
I don't know if it's a bug or just a missing validation / information for the project name field. 
Thought it was worth mentioning.

Cheerz!

P.S.: Btw,. really cool app! Keep it up  😉

**Comment by eneiluj** [comment]
Hi!

The project name is in fact different from the project ID. When you create a project, you just provide a name. An ID is generated from this name and returned by the creation API endpoint. When you get the project list, for each project you get the name, the ID and a lot of stuff. Project IDs must be used everywhere in the API to identify :grin: projects when requesting stuff.

Thanks for the compliment and the enthusiasm!

P.S. What is you app? What's the target platform? Are you going to publish it on a Free license?

**Comment by stanislavhannes** [comment]
Ahh ok I get it. I wasn't using the API endpoint for creating a project. Rather, I assumed that one had already been created with the Cospend UI. But that gives me the idea to include this possibility as well.

About the app: It's a shared shopping list where every member of the project can add, delete and check off an item on/off the list. When it's checked off the list, then an popup modal appears that asks besides other fields for the price and with whom to share the checked item. This data is sent to cospend and creates a bill there. It is primarily useful for shared flats. 
The toolstack is Laravel, Vuetify and Inertia.js and it's going to be open source for sure 🐱‍🏍

The MVP is almost done, just want to get a few tickets done before publishing.
II'll let you know when I have published it. Maybe you can mention it in your readme 😅
