### ISSUE TITLE
Letter Avatars cause CPU spikes

### ISSUE THREAD

**Issue by normen** [eneiluj/cospend-nc#37]
Hi.

First of all thanks for this software, it's awesome!

Since some updates ago I seem to see severe CPU spikes when a lot of different participants with a "letter" avatar are displayed. The avatars also load very slowly in the browser, probably due to that. It seems that the avatars are re-generated each time?

I can't see anything suspicious in the logs and my nextcloud is set up as a fpm service with a redis cache server attached, so its usually quite snappy.

Cheers,
Normen

**Comment by eneiluj** [comment]
Hi and thanks for the compliment!

Part of the UI was still using a legacy avatar generator written in Cospend. This generator is supposed to cache images but maybe the cache mechanism itself is slow. Anyway I got rid of this internal avatar system to only use Nextcloud Vue components. Let's see if it has a positive impact on your side.

Could you try `v1.3.0-6-nightly` which is out?

**Comment by normen** [comment]
Sure, is there an easy way to install a nightly version through the normal tools? Do I have to use the OCC app:install command?

**Comment by eneiluj** [comment]
Easiest way to install the nightly is with
```
occ app:update --allow-unstable cospend
```

**Comment by normen** [comment]
Yep, they appear pretty much instantly now and theres no more CPU spikes. Thanks!

**Comment by eneiluj** [comment]
Yay thanks a lot for the feedback. Next release is coming soon.
