### ISSUE TITLE
Data storage location

### ISSUE THREAD

**Issue by florisre** [eneiluj/cospend-nc#39]
I am trying to restore Cospend from a broken installation. Where is the data kept? I restored `appdata[hash]/cospend` but this had no effect. Any advice would be greatly appreciated, as unfortunately my weekly updates had stopped working before I noticed any problem.

**Comment by eneiluj** [comment]
Hi, what do you mean by broken installation? Did something in Cospend break? Or was something else wrong with your Nextcloud?

All Cospend data is stored in Nextcloud database in tables which names begin with `oc_cospend_`.

If you reinstalled Nextcloud, you can then try to export all Cospend tables from your old databse and insert them in the new one. Beware that if you already created Cospend projects in the new Nextcloud, there might be row ID conflicts when inserting. Make sure your Cospend table in the new instance are empty.

**Comment by florisre** [comment]
thanks for the quick reply! This is exactly what I was looking for. Unfortunately, my old installation's database seems to be broken. So, I am afraid all is lost.

To clarify, there was no issue with cospend, I was just seeking the exact information you gave, Thanks!

**Comment by eneiluj** [comment]
What kind of database were you using on the old Nextcloud instance? Are you sure nothing can be done? How did it break?

**Comment by eneiluj** [comment]
Closing this for now. Feel free to reopen if needed.
