### ISSUE TITLE
Wiki doesn't exist

### ISSUE THREAD

**Issue by Merrit** [eneiluj/cospend-nc#4]
Was trying to figure out why I don't have a "New bill" button, all instructions say refer to: ${wiki doc}

All wiki links just redirect back to the main repo page.

**Comment by simonspa** [comment]
Probably @eneiluj didn't port them to GitHub yet, here is the link: https://gitlab.com/eneiluj/cospend-nc/-/wikis/home

**Comment by Merrit** [comment]
I see.

Since all it says there is "There is not much to say here." I will post a screenshot of the issue:

![Screenshot_20201028_173044](https://user-images.githubusercontent.com/9575627/97508773-d963a480-1956-11eb-999a-67f62e6abae3.png)

There is a button for "New project", but not "New bill" as in the screenshots.

**Comment by eneiluj** [comment]
@Merrit You need at least 2 members to see the "new bill" button. Do you have 2 project members?

**Comment by Merrit** [comment]
I don't actually, I wanted to evaluate if the app would fit our needs before getting anyone else to look at it.

**Comment by eneiluj** [comment]
Project members are not Nextcloud users. Just create 2 of them in Cospend and you're good to go.

**Comment by Merrit** [comment]
I see! Thank you, can have a go at it now :heart:
