### ISSUE TITLE
Cospend widget on Dashboard

### ISSUE THREAD

**Issue by bricebou** [eneiluj/cospend-nc#40]
Hi,

First, thanks for this great app !

I have an issue with the Cospend widget on the Dashboard : it shows no recent activities, even when I add a new item...

Latest version of Nextcloud, Cospend up to date.

Thanks again and in advance !

**Comment by eneiluj** [comment]
The widget uses the activity feed. it will display the same things as in the activity app. Do you see the expected content in the activity app?

Keep in mind that your activity not listed in your activity feed.

**Comment by bricebou** [comment]
Well, that's it ! Even if in Nextcloud 21, I see my own activities in the activity app feed.

Thanks for your quick answer :)
