### ISSUE TITLE
"for whom" section changes in all bills, when creating new bill with custom type

### ISSUE THREAD

**Issue by mayonezo** [eneiluj/cospend-nc#42]
How to reproduce:

1. Create new bill
2. Change bill type to anything other than "Classic, even split" (do not click "Create the bills" though!)
3. Select another bill -> Under section "for whom" you will see "personal amount", "custom amount" or "custom share number" instead of what was selected for the bill and the share value

Expected behavior: "for whom" section of other bills should not change when creating new bill.

**Comment by eneiluj** [comment]
Thanks a lot for the issue. It's fixed and will be included in next release.

In the meantime, if you want to try it, it's available in v1.3.0-5-nightly.
