### ISSUE TITLE
No comma replacement in Bill type section

### ISSUE THREAD

**Issue by ndi123** [eneiluj/cospend-nc#44]
When entering personal amount in the bill type section there is no comma replacement to a point. In the regular section there is a replacement from comma to a point. The missing replacement results in wrong results because everything after the comma will be ignored.

Example:

![grafik](https://user-images.githubusercontent.com/34609222/113458766-b2ccfc80-9413-11eb-97e4-f033ebfcc89c.png)

![grafik](https://user-images.githubusercontent.com/34609222/113458788-c5dfcc80-9413-11eb-8c2c-0915b8533b9b.png)

**Comment by eneiluj** [comment]
Thanks for the bug report. It should be fixed now in v1.3.1-1-nightly which was released. Could you give it a try?

This issue was also affecting custom owed amounts. I thought it was alright because comas were replaced when evaluating a formula but not when just writing a simple number with a coma :grin:. So `2,2 + 1` was alright but `2,2` was not. It's now ok.

**Comment by ndi123** [comment]
Thank you for the quick fix. It's working now when using commas 😃 There ist one cosmetic thing: When entering amount in main section comma will immediately replaced with point (but only when entering a number with comma - when using simple math only the first number with comma will be replaced). This replacement is not happening in custom owed amount.

One stupid question: Why `2.4+1.2` will be displayed as `3.5999999999999996`?

**Comment by eneiluj** [comment]
Thanks for your precise remarks. I think everything is fixed in latest nightly.

Strange javascript decimals is now ok and comas are replaced on each new character when typing main amount.

Could you try it?

**Comment by ndi123** [comment]
Strange decimals are fixed and comma replacement ist working in main amount 👍 To have a consistent behaviour comma replacement in personal amount would also make sense in my opinion.

**Comment by eneiluj** [comment]
You're right, thanks for the feedback and the remarks.

Next release is coming soon.

**Comment by ndi123** [comment]
I have now noticed another problem: When I enter a two-digit number followed by a comma/point then the point will be deleted when ich try to enter the first number after the comma.

![GIF 11 04 2021 23-02-27](https://user-images.githubusercontent.com/34609222/114321272-49877080-9b1a-11eb-974c-7d384b4de348.gif)

**Comment by eneiluj** [comment]
This should be fixed in v1.3.1-6-nightly. Could you try it?

**Comment by ndi123** [comment]
It's fixed 👍

**Comment by eneiluj** [comment]
Yay! Thanks
