### ISSUE TITLE
Time 00:00 is assigned to previous day

### ISSUE THREAD

**Issue by pawlosck** [eneiluj/cospend-nc#45]
Set date 2021-04-01 00:00 in bill.
Go to statistics. Bill with time 2021-04-01 00:00  is assigned to previous month (March).

**Comment by eneiluj** [comment]
Thanks for the bug report. Php uses UTC timezone by default. I thought it was using the system one. Timezone is now obtained via Nextcloud built-in objects. I don't know where it comes from (passed with the browser or deduced from user settings...) but it works fine on my side (getting `Europe/paris`).

v1.3.1-3-nightly is out with a fix. Could you try it?

**Comment by pawlosck** [comment]
Where are nightly builds?
I will try to check it at weekend.

**Comment by eneiluj** [comment]
If you want to install them manually, all releases (including the nightly ones) are in this project's release section. They are also in the appstore.

There is an easier way to install it:
```
occ app:update --allow-unstable cospend
```
This will get and install the latest nightly. Tell me if you need advice to run the occ command.

**Comment by pawlosck** [comment]
Tested and it works correctly.
Tell me, how to restore stable version of cospend?

**Comment by ndi123** [comment]
This is how i am going back to the latest stable version:

```
occ app:remove cospend
occ app:install cospend
```

**Comment by pawlosck** [comment]
@ndi123 Thanks
