### ISSUE TITLE
[Feature] Add option to skip time or set default time

### ISSUE THREAD

**Issue by pawlosck** [eneiluj/cospend-nc#46]
Add option, to skip time in bill or option to set default time, for example 00:00 or 23:59

**Comment by eneiluj** [comment]
Why not. There's a new setting in bottom left area. It changes the type of the bill edition date picker.

Could you try v1.3.1-4-nightly which is out there with this change?

**Comment by pawlosck** [comment]
Tested and it works, but I would like to suggest, to set time to 0:00 when user create new bill.
Case1. User create bill and left current date (time is set for current time, e.g. 15:10)
Case2. User create bill and change date (time is set for 0:00)
Should be the same time, when you change date or not.

**Comment by ndi123** [comment]
I am missing the confirmation button in the date picker. This is especially helpful on touschreens.

(Also i would like if the date picker could show every minute and not the 5 minute steps.)

**Comment by eneiluj** [comment]
Right, right and right. Here are the changes in v1.3.1-6-nightly:
* re-enable date confirmation
* set minute step to one minute
* set new bill time to 00:00:00
* change bill date format depending on useTime setting

@ndi123 @pawlosck Could you give it a try?

**Comment by pawlosck** [comment]
- re-enable date confirmation - Tested -> OK
- set minute step to one minute - Tested -> OK
- set new bill time to 00:00:00 - Tested -> OK
- change bill date format depending on useTime setting - Tested -> OK

I found small bug, but it's not reproducible 100%.
Current date: 2021-04-12
Case1: Set format for date/time. Open date/time picker and press the current date (2021-04-12) (don't change selected date). Date picker is closed and time picker is not opened. I don't know, how to reproduce it. It happen few times.

Case2: Set format for date/time. Open date/time picker and press OK (left selected date) -> Time picker is not opened. It's reproducible 100%

**Comment by pawlosck** [comment]
How to update unstable version? I had to remove cospend, install stable version and next use 
sudo -u www /usr/bin/php /nextcloud/occ app:update --allow-unstable cospend
to install unstable version.

**Comment by ndi123** [comment]
Looks good from my perspective.

**Comment by eneiluj** [comment]
@pawlosck
> Case1: Set format for date/time. Open date/time picker and press the current date (2021-04-12) (don't change selected date). > Date picker is closed and time picker is not opened. I don't know, how to reproduce it. It happen few times.

Never happened to me. I don't do anything fancy here, just using the datepicker component provided by @nextcloud/vue library. There might be a bug in this component. Let's see if other users report a similar issue.

> Case2: Set format for date/time. Open date/time picker and press OK (left selected date) -> Time picker is not opened. It's reproducible 100%

This is how the datepicker component works. Time is shown only if a date is picked.

Let's close this. Feel free to reopen if you need.

**Comment by pawlosck** [comment]
Yes, it's probably problem with Nextcloud library.
