### ISSUE TITLE
Bill deletion doesn’t appear in activities

### ISSUE THREAD

**Issue by whtv** [eneiluj/cospend-nc#48]
Creation and changing of a bill appears under recent activities in Nextcloud, but deletion of a bill doesn’t.

**Comment by eneiluj** [comment]
Thanks for the bug report. It's now fixed and available in latest nightly release (v1.3.1-5-nightly). Could you try it and check activities work as expected?

**Comment by whtv** [comment]
Thanks for the quick fix! Works as expected. However, the German traslation was off, I updated it on Crowdin.

**Comment by eneiluj** [comment]
Nice! Thanks for the feedback and for the translation!
