### ISSUE TITLE
[Feature request] Button "Repeat now" should be available, when user choose any option from field "Repeat"

### ISSUE THREAD

**Issue by pawlosck** [eneiluj/cospend-nc#49]
When user choose any option from field "Repeat", button "Repeat now" should be available immediately, not after adding new bill.
Currently, it's not intuitive..

**Comment by eneiluj** [comment]
Well technically you can't repeat a bill that does not exist. It needs to be created first so it exists in the database. Then the "repeat now" button triggers the repetition process (same one that is launched by NC background jobs). This process can only repeat what already exists in the DB.

Let's say we display the "repeat now" button in bill creation form. I would need to create the bill before repeating it. I think it will also not be very intuitive to have the choice between the "create" and "repeat now" buttons.

Anyway this "repeat now" button is a small extra feature for users who don't have an operational cron setup. The classic way to repeat bills is to wait and it's done automatically.

**Comment by pawlosck** [comment]
So maybe you should remove "repeat now" button? Bill should be repeated, when user choose repeat function and create bill.
For me, it's most logical solution.
