### ISSUE TITLE
Copy Project

### ISSUE THREAD

**Issue by alexthecamel** [eneiluj/cospend-nc#5]
Hi, just found Cospend, loving it so far.

Is there any way to copy a project, I have setup all the household bills for a month and who is paying what, I presume having them repeat would keep adding Bills to this project at the appropriate time, but I would like to treat each month in isolation.

Is there anyway for me copy a project keeping all splits etc in tact but avoid having to re enter them all in the new Project?

Thanks

**Comment by eneiluj** [comment]
You can export the project to csv, rename the file and import it back. Feel free to reopen if necessary.
