### ISSUE TITLE
[Feature request] Add new section (payment mode) into page Statistics

### ISSUE THREAD

**Issue by pawlosck** [eneiluj/cospend-nc#50]
Could you add new section (payment mode) into page Statistics?
For example.
Credit card - 100
cash -            200
transfer -       1000

Something like section "Monthly stats per category"

**Comment by eneiluj** [comment]
Yes why not. There are now 3 more stats elements:
* monthly payment mode table
* monthly payment mode line chart
* total payment mode pie chart

At some point it could be useful to allow hiding some charts or to find a way to make this stats page more readable.

Anyway, this is available in latest nightly: v1.3.2-2-nightly

**Comment by pawlosck** [comment]
Thanks. Generally looks great, but line chart is broken. Item between 800 and 900 is wrong. Cash, as you see is wrong too.
![image](https://user-images.githubusercontent.com/3769853/115083804-40c2e000-9f08-11eb-84ce-46aedd144666.png)

**Comment by eneiluj** [comment]
@pawlosck The chart is actually correct :grin:. It is less confusing when there are more than one X-axis (month) value because colored areas are visible.

Y points don't have absolute positions but rather relative to the one before. Your cash point is 16.5 higher than the credit card one. The transfer (blue) is ~460 higher than the cash.

Other charts are behaving exactly like that too.

**Comment by eneiluj** [comment]
And thanks for your feedback :grin:!

**Comment by pawlosck** [comment]
> @pawlosck The chart is actually correct grin. It is less confusing when there are more than one X-axis (month) value because colored areas are visible.
> 
> Y points don't have absolute positions but rather relative to the one before. Your cash point is 16.5 higher than the credit card one. The transfer (blue) is ~460 higher than the cash.
> 
> Other charts are behaving exactly like that too.

Ok, a understand now. So could you add second type of chart? Simple chart with dots and lines (without colored areas)?
It would be great, if you add option to switch beetwen charts directly next to chart.

**Comment by pawlosck** [comment]
> And thanks for your feedback grin!

No problem. Your app is great. There are some missing features, but generally is ok.
