### ISSUE TITLE
Stats won't show anything

### ISSUE THREAD

**Issue by Byter3** [eneiluj/cospend-nc#52]
Stats won't show anything if payment **mode set to all** and the **minimum date is from the previouse year**

Nextcloud 20.0.9
Coospend 1.3.2

**Comment by eneiluj** [comment]
Thanks for the bug report.
I can't reproduce the bug.
Could you give more details about your context.
* What are the dates of the first and last bills?
* What stat filter values are you setting?
* Is there any error in the browser console log? And/or in nextcloud.log?
* Any other thing that can help :grin:

**Comment by Byter3** [comment]
first and last date: 2020. 04. 008. - 2021. 05. 02.
Filter values are default, should see all the bills. (It works only when I set the start date to 2020. 12. 19. any older dates it wont show anything)
I can't see anything related in the browser's console. I tried with the new Edge and with Firefox.
I can't see anything inside nexcloud's log either. 
Circles are just circling where the charts should appear. I'm not sure if this bug appeared after the new update, but I know it worked couple of weeks ago.

**Comment by jonasbb** [comment]
I see the same problem after updating to 1.3.2. The previous version (1.3.0) worked before. I am using NC 20.0.9 and Firefox 88.0. I am seeing those error messages in the browser console though:

```
TypeError: t is undefined
    getPaymentModeNameIcon Statistics.vue:910
    monthlyPaymentModeStats Statistics.vue:573
    VueJS 3
    Te Statistics.vue:7
    VueJS 7
vue.runtime.esm.js:1890:10
```

**Comment by eneiluj** [comment]
Wow that was a stupid mistake. Sorry. v1.3.3 is on the road and fixes it.
GitHub actions service (which produces and publishes Cospend releases) is having problems today so let's wait'n'see.
https://github.com/eneiluj/cospend-nc/actions/runs/817283397

**Comment by jonasbb** [comment]
Both 1.3.3 and 1.3.4 work for me to show the stats. Thanks for fixing it so quickly.
