### ISSUE TITLE
Error loading left menu and Javascript error

### ISSUE THREAD

**Issue by susinths** [eneiluj/cospend-nc#54]
On NC 20 on stable20, i get the left menu trying to load for a while and then i see a big white window with Javascript error.
![Screenshot from 2021-05-28 10-31-39](https://user-images.githubusercontent.com/2558738/119956255-3123c600-bfa1-11eb-99f8-f430d5a56a5e.png)

In the browser console i see:

cospend-main.js?v=709c0cc1-27:2 GET https://nextcloud.mydomain/index.php/apps/cospend/projects 500 (Internal Server Error)
(anonymous) @ cospend-main.js?v=709c0cc1-27:2
e.exports @ cospend-main.js?v=709c0cc1-27:2
e.exports @ cospend-main.js?v=709c0cc1-27:2
Promise.then (async)
l.request @ cospend-main.js?v=709c0cc1-27:2
a.forEach.l. @ cospend-main.js?v=709c0cc1-27:2
(anonymous) @ cospend-main.js?v=709c0cc1-27:2
f @ cospend-main.js?v=709c0cc1-27:2
getProjects @ cospend-main.js?v=709c0cc1-27:2
created @ cospend-main.js?v=709c0cc1-27:2
We @ cospend-main.js?v=709c0cc1-27:2
sn @ cospend-main.js?v=709c0cc1-27:2
e._init @ cospend-main.js?v=709c0cc1-27:2
o @ cospend-main.js?v=709c0cc1-27:2
(anonymous) @ cospend-main.js?v=709c0cc1-27:2
init @ cospend-main.js?v=709c0cc1-27:2
(anonymous) @ cospend-main.js?v=709c0cc1-27:2
A @ cospend-main.js?v=709c0cc1-27:2
hi.nodeOps @ cospend-main.js?v=709c0cc1-27:2
e._update @ cospend-main.js?v=709c0cc1-27:2
a @ cospend-main.js?v=709c0cc1-27:2
bn.get @ cospend-main.js?v=709c0cc1-27:2
bn @ cospend-main.js?v=709c0cc1-27:2
e @ cospend-main.js?v=709c0cc1-27:2
Dn.$mount @ cospend-main.js?v=709c0cc1-27:2
e._init @ cospend-main.js?v=709c0cc1-27:2
Dn @ cospend-main.js?v=709c0cc1-27:2
kn @ cospend-main.js?v=709c0cc1-27:2
xn @ cospend-main.js?v=709c0cc1-27:2
(anonymous) @ cospend-main.js?v=709c0cc1-27:2
Promise.then (async)
c @ cospend-main.js?v=709c0cc1-27:2
(anonymous) @ cospend-main.js?v=709c0cc1-27:2
(anonymous) @ cospend-main.js?v=709c0cc1-27:2

**Comment by eneiluj** [comment]
Which version of Cospend are you using?
Could you check if any error pops up in nextcloud.log when you load Cospend's page?

I can't reproduce the issue with a fresh NC 20 install and latest Cospend.

**Comment by susinths** [comment]
version 1.3.4
"app":"index","method":"GET","url":"/index.php/apps/cospend/projects","message":{"Exception":"RuntimeException","Message":"erinaunofficial does not exist

**Comment by eneiluj** [comment]
:grin: Yes, the browser has no influence on server-side errors like this one.

I'm trying to fix the issue and to cleanup this part of the code. I'll publish a nightly soon and keep you updated.
Thanks for the bug report by the way.

**Comment by eneiluj** [comment]
v1.3.5-1-nightly is out. It will be available in the appstore in a few minutes (one hour at most). You can install it via occ. Here is an example to adapt to your context:

sudo -u www-data php /var/www/html/nextcloud/occ app:update --allow-unstable cospend

To get back to the official release, in the web interface, just disable the app, remove it and install it again.

I'll keep on cleaning this kind of stuff.

**Comment by eneiluj** [comment]
Feel free to reopen if the problem is still there.
