### ISSUE TITLE
Feature request: Search for a bill

### ISSUE THREAD

**Issue by mr-manuel** [eneiluj/cospend-nc#55]
Hello,

thank you for this great project. Would it be possible to add a search function to search for a string in the "what" or "comment" field?

**Comment by eneiluj** [comment]
Hi,

Thanks for your enthusiasm.

There already is a unified search provider for Cospend. Just search in the top-right corner and you'll get Cospend results in there.
Additionally, if the current displayed app is Cospend when you search, the current bill list will be filtered according to the current search query.

Search is only done with the "what" for the moment. But it's a good idea to use the "comment" too. It's now done and will be included in next release. Search results are now also including the bill date and currency name. Search is now case insensitive.

It would be nice if you could try it before the release and confirm it works fine. It's available in latest nightly release (v1.3.5-2-nightly) which you can get with an occ command:

```
occ app:update --allow-unstable cospend
```
When you want to get back to normal releases, just disable and remove the app from app settings and reinstall it. You won't loose any data.

**Comment by eneiluj** [comment]
Feel free to reopen if the feature does not properly works.
