### ISSUE TITLE
Crash after update

### ISSUE THREAD

**Issue by dmkoder** [eneiluj/cospend-nc#56]
I have just updated to the version 1.3.5 and app is not working anymore.
Attached you can find more details:
[cospend.log](https://github.com/eneiluj/cospend-nc/files/6673088/cospend.log)

**Comment by eneiluj** [comment]
I can't reproduce this issue on my test instances. Could you check that the file `/var/www/.../nextcloud/apps/cospend/lib/Service/ProjectService.php` exists and is not empty?

Which version of Nextcloud are you running?
Which version of Php?
Is there any other error before or after the one you attached?

**Comment by dmkoder** [comment]
The file exists and it is not empty.

Nextcloud version: 20.0.10
Php version: PHP 7.2.24

Here is the only other error where cospend is mentioned.
[cospend-1.log](https://github.com/eneiluj/cospend-nc/files/6675402/cospend-1.log)

**Comment by eneiluj** [comment]
Ok so your problem is most likely related with PHP 7.2 compatibility. I realized some recent changes break it. 
v1.3.6 has been published and should work in your environment. Could you check if it does?
Thanks a lot for the bug report and the feedback.

**Comment by dmkoder** [comment]
Yes, I have updated it and it is working!
Thank you very much for your effort!

**Comment by eneiluj** [comment]
Yay! Thanks for the quick feedback!
