### ISSUE TITLE
Exception when changing access level of a Nextcloud user

### ISSUE THREAD

**Issue by rettenbs** [eneiluj/cospend-nc#57]
Hi, i get an exception when changing the access level of a Nextcloud user in a Cospend project.

**Steps to reproduce:**

1. Create a new Cospend project
2. Add a Nextcloud user to the project
3. Change the access level of the new user

**Result:**
You can see an error message pop and the access level is not changed.

The Nextcloud log shows the following error:
```
[index] Error: Exception: Call to undefined method OC\DB\QueryBuilder\QueryBuilder::executeStatement() at <<closure>>

0. /srv/www/nextcloud/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Cospend\Cont ... }}, "addUserShare")
1. /srv/www/nextcloud/lib/private/Route/Router.php line 309
   OC\AppFramework\App::main("OCA\\Cospend\\C ... r", "addUserShare", OC\AppFramework\ ... {}, {projectid: "ges ... "})
2. /srv/www/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/cospend/p ... e")
3. /srv/www/nextcloud/index.php line 37
   OC::handleRequest()

POST /nextcloud/index.php/apps/cospend/projects/geschenke/user-share
from 146.52.193.171 by sebastian at 2021-06-19T23:59:21+00:00
```

**Version:**
Nextcloud 20.0.10
Cospend 1.3.6

**Preanalysis:**
I did a bit of digging the code. The undefined function is added for Nextcloud 22. Relevant PRs:
* https://github.com/nextcloud/server/pull/23665
* https://github.com/nextcloud/server/pull/26877

I am not sure if this is Nextcloud server issue or a Cospend issue. So far, I have seen this issue only with Cospend and no other app.

**Workaround:**
I copied the new `executeStatement` function from Nextcloud 22 to my installation. The function is basically a wrapper for `execute`. This resolved the issue for me.

**Comment by eneiluj** [comment]
Thanks for the bug report. This is a mistake. I mixed up the changes from 2 branches. The new db method call shouldn't be in v1.3.6.

v1.3.7 is out and should work fine with Nextcloud 20. Could you confirm?

**Comment by rettenbs** [comment]
v1.3.7 fixed the issue. I could remove the workaround. Thanks for the quick fix.

**Comment by eneiluj** [comment]
Thanks for the feedback!
