### ISSUE TITLE
[Request] Statistics enhancement - Spent per member per month

### ISSUE THREAD

**Issue by Raspikabek** [eneiluj/cospend-nc#58]
Request for the addition of a new table + graph of a `Spends per member per month` in the **Monthly stats per member** existing section

This will bring a bit more value to determine who spends more or less regardless who has paid for it. Existing **Global Stats** already displays the total sum of this per member, however this is not reported in a monthly basis in in details below.

Thanks!

PS: amazing job! I fell in love with this app! Keep going the good work!

**Comment by eneiluj** [comment]
Thanks for the suggestion and for the love!

I like the idea and it was quite quick to implement.
It's available in [latest nightly build](https://github.com/eneiluj/cospend-nc/releases/download/v1.3.8-1-nightly/cospend-1.3.8-1-nightly.tar.gz). Small problem if you want to try it (which would be great): Cospend is now only compatible with Nextcloud >= 22. So you can install this nightly on Nextcloud 22RC1 which is available in https://download.nextcloud.com/server/prereleases/

There has been some changes in the line chart style, datasets are not stacked anymore and colored areas are not drawn anymore. Those line charts are more classic (and readable) now. I'm interested to know what you think about those changes if you get to try the nightly.
Cheers

**Comment by Raspikabek** [comment]
Astounding! Thanks for the quick reply. I tried myself by forking the project and I saw the Statistics part is a bit 'hard-coded' and started myself to see how could I create a PR for this, didn't have time to fully understand the structure of the 'stats' variable and its content though. 

Anyway, thanks! 

I'm running Nextcloud with `linuxserver/nextcloud` image, right now in version `21.X`   if I find some time I'll try to setup another test environment for this, otherwise I'll have to wait till `v22` is fully released.

Again, thanks a million!

**Comment by eneiluj** [comment]
Feel free to reopen if this feature does not properly work.

**Comment by Raspikabek** [comment]
I updated the latest version a while ago, finally got a chance to take a look into this and I've to say: BIG THANKS! It works flawlessly and now makes tons of sense. 

Thanks for hear me out and implementing this new feature request. You are a gent!
