### ISSUE TITLE
Automatically Share When Adding NC User as Project Member

### ISSUE THREAD

**Issue by simonspa** [eneiluj/cospend-nc#6]
I was a bit confused when playing around with Cospend 1.1.1 on NC 20.0.1 by the following situation:

* Log in as User1
* Created new project "Test"
* Add User2 and User1 to project "Test"
* Add some bills
* Log out and back in this time as User2
* Expect to see the Cospend project "Test" of which this user is a member
* Observe that nothing is there

After a while I realized that it's not enough to add a user as member, but I also need to share the project with that user.

Would it be possible to automate this? If a new project member is added and this member is a NC user, a share is automatically created?

**Comment by eneiluj** [comment]
True that. Will do. Thanks for the suggestion!

**Comment by eneiluj** [comment]
Ok done. A participant shared access is added (if it does not exist already) when adding a user as member and when associating a user to a member.

The access is not deleted when the member is deleted or the association is broken by renaming the member. That will do for the moment. What do you think?

**Comment by simonspa** [comment]
What is the reason for not removing the share with the member?

If there would be a way to tell if a share was added automatically or manually it could be removed in case it was just the auto-sharing. At least the way I think about this, this would best portray the expected behavior of a novice user:
* If I shared this project with someone, the share should stay until I delete it
* If I add someone as member, that person should have access to the project
* If I remove a member, that person should not have access to the project anymore

**Comment by eneiluj** [comment]
> If I shared this project with someone, the share should stay until I delete it

Yeah that's exactly why I didn't directly implement automatic deletion. Well adding a "manually added" DB field for shared accesses would work but it feels like a trick.

I'll probably do it soon anyway.

**Comment by eneiluj** [comment]
Ok done, automatically added shared accesses are now deleted when renaming the member (breaking the user<->member link) or deleting/disabling him/her.

Existing shared accesses are considered manually added. A choice had to be made.

Let's wait until someone (anyone, really :grin:) has tested this to close the issue.

**Comment by simonspa** [comment]
I tested this on my local instance:

* When adding myself as member, I get the error `Failed to add shared access: "No such user"` probably because I'm trying to share with myself
* When adding another user, a share is created properly
* When removed from the project, the share is removed, too
* When first sharing to a user and then adding them as member, a removal from the project leaves the share intact!

Conclusion - works perfectly apart from filtering out the own user from sharing.

**Comment by eneiluj** [comment]
> When adding myself as member...

Ok this is solved. Adding the project owner as a member or associating a member to him/her won't crash anymore. Nice catch! Thanks a bunch.

Let's close this once you confirm it's fine now.

**Comment by simonspa** [comment]
Confirmed.
