### ISSUE TITLE
HTML entities instead of characters in settlement title

### ISSUE THREAD

**Issue by sihagen** [eneiluj/cospend-nc#60]
The h2 title on the settlement page is printed with html entities instead of the corresponding character. In my case "`&amp;`" is printed instead of "&". In the navigation list this works just fine.

https://github.com/eneiluj/cospend-nc/blob/44b4f1bbe91cc346b045e040f53349cb5fb73f7a/src/Settlement.vue#L5

- Nextcloud version: 20.0.10
- Cospend version: 1.3.7

**Comment by eneiluj** [comment]
Thanks for this issue. This can be found in other places too. I fixed a bunch of them. Still looking for others.

It will be included in v1.3.9.
