### ISSUE TITLE
Kiwi Browser support

### ISSUE THREAD

**Issue by niggiover9000** [eneiluj/cospend-nc#61]
Not sure, wether this is a problem with my configuration or a problem with kiwi browser itself.
I cannot access Cospend from Kiwi Browser on Android. It works with Chrome on Android.
Let me know, if you need further information.

Thanks in advance!

**Comment by eneiluj** [comment]
Hi, I tried to access Cospend on my tests instances and on my production instance...and it always works. I can't tell what's happening on your side.

Anyway, as Kiwi is based on Chromium (like Brave, Chrome and many others) I don't see why it wouldn't work.

**Comment by eneiluj** [comment]
Did you try with another device?
Closing this for now but feel free to reopen if needed.
