### ISSUE TITLE
Category doesn't show the full list

### ISSUE THREAD

**Issue by Synochy** [eneiluj/cospend-nc#64]
Since the last update the category doesn't show the full list when clicking on it :
![Capture d’écran 2021-07-26 201108](https://user-images.githubusercontent.com/20789073/127037755-31fdfc0b-cbe4-4fc0-89a0-296867bbb1f3.png)

Nextcloud 22.0.0
Cospend 1.3.10
Breeze Dark 22.0.0

**Comment by eneiluj** [comment]
Thanks for this bug report.

It's now fixed and shipped in latest nightly (v1.3.11-1-nightly). Could you try it?
You can get it with an occ command:
```
occ app:update --allow-unstable cospend
```
When you want to get back to normal releases, just disable and remove the app from app settings and reinstall it. You won't loose any data.

**Comment by Synochy** [comment]
Everything works perfectly !

Thanks for the fix

**Comment by eneiluj** [comment]
Thanks for the feedback!
