### ISSUE TITLE
Cannot add member through public link

### ISSUE THREAD

**Issue by la-balisa** [eneiluj/cospend-nc#68]
Hi. I currently own a shared Cospend project, and we realized that guests cannot add a new member.

Config : 
Nextcloud 21 (Dockerized)
MariaDB NC database
Cospend 1.3.7
Tested on Firefox 78.9 and Chromium 89

Steps : 
 - Create a new project
 - Create a public link, grant it Maintainer or Admin permission
 - Open the link in a new (private) browser window
 - Go to Settings (or tree-dots-menu -> Add member)
 - Enter a new username -> there is no way to validate it (no button, and Enter key not doing anything) ; it seems to just do a search through the existing members, but with always no results

I expect this menu to have the same behavior as when logged as project-owner : it displays a "Create simple member" button when typing a username, and Enter key does the same.

**Comment by eneiluj** [comment]
Thanks for the bug report. I'll fix this in a few weeks.

**Comment by eneiluj** [comment]
The bug was quite simple to fix. Finally it did it. It's available in latest nightly build (only compatible with Nextcloud 22, sorry).

If at some point you upgrade to NC 22 and want to try the nightly, you can get it with an occ command:
```
occ app:update --allow-unstable cospend
```
When you want to get back to normal releases, just disable and remove the app from app settings and reinstall it. You won't loose any data.

**Comment by la-balisa** [comment]
Nice, thank you :-)

I will try as soon as i update to NC 22 ! (but i still have to figure how to check which apps will be disabled before updating, as it seems many useful apps are broken right now...)

**Comment by eneiluj** [comment]
You can check your apps compatibility on the appstore website, you can see [there](https://apps.nextcloud.com/apps/cospend#downloads), for example, that Cospend v1.3.7 is compatible with NC 20 and 21 and v1.3.10 with NC 22.

It would be great if you would be able to try the nightly before the next release :grin:.

**Comment by la-balisa** [comment]
I just setup a test NC22 instance, and with nightly (1.3.11), but sadly guest link functionality seems to be totally broken :(
Apart from the header (NC logo + "Cospend public access ; Project test" text), the page is totally blank when accessing public link from a private browsing session (Firefox or Chromium).

Reverting to Cospend 1.3.10 (by uninstalling and reinstalling it) fix it (but does not fix the original bug).

**Comment by eneiluj** [comment]
I don't know how this happens to you. Guest access works fine with v1.3.11-6-nightly on multiple test instances on my side.

Any error in the browser log or server log?

**Comment by eneiluj** [comment]
Or it can be a browser cache issue? You can try to refresh the guest access page with CTRL+F5

**Comment by la-balisa** [comment]
Every try is done through Ctrl+F5, and i tried from 2 differents browsers.
I have no idea neither :/ I'm don't know how to make sure i'm on 1.3.11-6, but it is installed through the command-line you provided to allow unstable upgrades.
I don't see anything suspicious in nextcloud.log (actually nothing after yesterday) or the docker logs for my container (only GET request from apache log).

Nextcloud is dockerized, and my web setup is behind a reverse proxy, and a NAT, maybe that could be related ?
I saved both (1.3.10 and 1.3.11) html source code (client-side), could that be useful ?

**Comment by eneiluj** [comment]
> I can also provide an access to my test server if you want (as i am not really able to use browser console, and such tools)

Yes why not. You can send me the details by e-mail if you want (check the [commits](https://github.com/eneiluj/cospend-nc/commit/7ffff1ec52c6157a7f0dbdafcaaa613c0d8b3203) of this project to get my address).

> I'm don't know how to make sure i'm on 1.3.11-6

The occ command should have told you.

> Nextcloud is dockerized, and my web setup is behind a reverse proxy, and a NAT, maybe that could be related ?

I don't think so.

> I saved both (1.3.10 and 1.3.11) html source code (client-side), could that be useful ?

Nope :grin:

**Comment by eneiluj** [comment]
Btw, thank you for your patience :grin:. We're going to figure this out.

**Comment by la-balisa** [comment]
Thanks goes to you for your work :)
I did not have dash-version numbers in the occ command, only 1.3.10 and 1.3.11. My command looked like : `docker exec -u www-data cloud_test sh -c "php /var/www/html/occ app:install cospend"`

Mail is sent if you want to test it !

**Comment by eneiluj** [comment]
Nice. I could spot the bug and fix it. It was about the accessibility app not being enabled in public pages.
The fix is included in the latest nightly (v1.3.12-3-nightly). Could you try it?

By the way, if you really want to make sure you're using the right nightly, you can download it manually from the appstore and place it in your apps directory.

**Comment by la-balisa** [comment]
It works fine with last version, either from app:update or manually unpacking the app !
Page is no longer blank, and member creation is working from guest access. Kudos :)
I think we can close the issue ?

**Comment by eneiluj** [comment]
Yay thanks a lot for the feedback. v1.3.12 is coming soon (thanks to you).
