### ISSUE TITLE
Display Content when View is Empty

### ISSUE THREAD

**Issue by simonspa** [eneiluj/cospend-nc#7]
Currently when opening a pristine Cospend, the view is just plain white, with the "Add project" button in the top right. In my view this is not optimal because as a user I have no feedback whether there are still thing loading in the background, taking ages, or if there literally is no content.

How about showing something like the photos app if there is nothing to show:
![image](https://user-images.githubusercontent.com/1677436/97671987-90603d00-1a89-11eb-9eb8-e9df8a22f1d6.png)

You could also use the beautiful illustrations from unDraw, e.g. "Receipt" or "Online payments"

![image](https://user-images.githubusercontent.com/1677436/97672265-02d11d00-1a8a-11eb-83fe-268d0baa3b64.png)

**Comment by eneiluj** [comment]
Yeah empty content needs to be improved. Will do!

**Comment by eneiluj** [comment]
Ok a simple empty content is now displayed for bill list and project list. If someone feels like improving it, great, if not, good enough.

**Comment by eneiluj** [comment]
Feel free to reopen if necessary.
