### ISSUE TITLE
Duplicate bill as new

### ISSUE THREAD

**Issue by TtuxX** [eneiluj/cospend-nc#70]
Hello @eneiluj!

First of all, let me thank you for your amazing app and all the wonderful features it offers.
It is regularly extremely useful to me. It is for me the most complete and well-rounded application in the nextcloud ecosystem. Thank you so much for such a powerful application you have created and for the time you put into making it better and better!

I'm planning a trip with a friend and we keep our accounts balanced by paying each other back.
However, sometimes I just want to "duplicate as new" an existing bill to change just a thing or two, but there is no option to do so.

Do you think it could be possible to have such an option to quickly duplicate as new an existing bill?

**Comment by eneiluj** [comment]
Hey!

Thanks for your compliments. Always a pleasure to know the app is appreciated!

And thanks for the good idea! Simple and useful. It was quite easy to implement. The way it's currently done can mess with disabled members. If a member's balance was brought back to zero and this member was disabled, it becomes hidden. Then if you duplicate a bill in which this member is involved, it will change the balance and show the member again. I'll fix that by automatically removing disabled owers in duplicated bill and keep you updated here.

So the feature is available in the latest nightly (v1.3.12-1-nightly). You can get it with an occ command:
```
occ app:update --allow-unstable cospend
```
When you want to get back to normal releases, just disable and remove the app from app settings and reinstall it. You won't loose any data.

**Comment by eneiluj** [comment]
Ok done. In v1.3.12-2-nightly, disabled owers are not included in duplicated bills and duplication is inhibited if the payer is disabled.

**Comment by TtuxX** [comment]
Dear @eneiluj, thank you so much for your awesome work and for your impressive reactivity, I just tried your new option and it is perfect and very straightforward! :) 
Do you know if we will also have the chance to get this option in the MoneyBuster app ?

Also - not sure why - but very recently Cospend app stopped displaying content, throwing an "Uncaught TypeError: OCA.Accessibility is undefined" as I had the Accessibility app disabled. 
I enabled it and Cospend app works great again in the browser.
Is it expected ? If not, would you prefer me to open another issue ?

**Comment by eneiluj** [comment]
Yay thanks for the feedback. I don't know about MoneyBuster, maybe it will but not soon.

About the Accessibility app issue. It's now solved, thanks for pointing on it. Could you try v1.3.12-3-nightly?

**Comment by TtuxX** [comment]
Everything now works perfectly, thank you so much Julien! :)

**Comment by eneiluj** [comment]
Well thank you again for your enthusiasm and great feedback. See you around!

**Comment by TtuxX** [comment]
@julien-nc Hi Julien and Happy New Year !! :) 

Thank you once again for this great and very useful functionality.
Would it be possible to also add a "Duplicate this bill" shortcut entry directly in the three-dots menu that we see on the picture hereunder?

![image](https://user-images.githubusercontent.com/6570830/210170485-6fa64398-44b9-4f8b-86d5-d7a1844b1e62.png)

Thank you very much !

**Comment by julien-nc** [comment]
Hey @TtuxX ! Happy new year to you too.

Nice idea. Done and available in v1.5.5-2-nightly. It would be nice if you could try it. You can also wait for v1.5.5.

**Comment by TtuxX** [comment]
Thank you very much Julien, it works great (tried on v1.5.5) !
