### ISSUE TITLE
Cannot add the owner of a project as a member

### ISSUE THREAD

**Issue by arnoldsuperstar** [eneiluj/cospend-nc#71]
I cannot add the owner/creator of a project (i.e. myself) as a member of that project. I can add any other user of the Nextcloud instance, but not myself.

This has changed recently, because previous projects includes me.

**Comment by eneiluj** [comment]
Which version of Cospend are you using? It's working fine with v1.3.10 on my side.

**Comment by arnoldsuperstar** [comment]
I'm using Cospend 1.3.7 on Nextcloud 21.0.3
I cannot have 1.3.10 on Nextcloud 21 according to the app store.

**Comment by eneiluj** [comment]
Ok I just tried with v1.3.7 and could reproduce the issue. It is fixed in v1.3.10 which is indeed only compatible with NC >= 22. You'll have to wait until you upgrade to NC 22 to get the fixed version. Sorry for the inconvenience.

**Comment by eneiluj** [comment]
Feel free to reopen if you still face this issue with NC >= 22.
