### ISSUE TITLE
TypeError: OCA\Cospend\Service\ProjectService::getProjectNames(): Argument #1 ($userId) must be of type string, null given, called in /var/www/nextcloud/apps/cospend/lib/Activity/CospendProvider.php on line 84

### ISSUE THREAD

**Issue by apg1980** [eneiluj/cospend-nc#75]
Hello,

i am getting this error with nextcloud 22.1.0 on ubuntu 20.04 apache2 with php8.0-fpm each time the cron is running:

`TypeError: OCA\Cospend\Service\ProjectService::getProjectNames(): Argument #1 ($userId) must be of type string, null given, called in /var/www/nextcloud/apps/cospend/lib/Activity/CospendProvider.php on line 84`

**Comment by eneiluj** [comment]
Duplicate of #74.
