### ISSUE TITLE
“No payment method” shown although payment method selected when creating new bill

### ISSUE THREAD

**Issue by PatrickJosh** [eneiluj/cospend-nc#78]
Hey,
in Cospend 1.3.14, when I create a new bill and select a payment method, “No payment method” is still shown. However, the payment method is saved correctly; when I save the newly created bill and reopen it, the correct payment method is shown. Then I can also change it and it is shown directly, the problem exists only when creating a new bill. This affects all payment methods, not only custom ones.

I'm using Nextcloud 22.1.0 with Cospend 1.3.14 on Ubuntu 20.04 LTS with all packages up to date, so I'm using php 7.4.3 and MariaDB 15.1.

**Comment by PatrickJosh** [comment]
If I haven't done anything wrong, then the nightly didn't fix it. I still have the same issue as before.

**Comment by eneiluj** [comment]
How did you install the nightly?
Did you try to reload Cospend with CTRL+F5 to make sure the page cache is cleared?

**Comment by PatrickJosh** [comment]
Sorry, I forgot to clear the page cache. Now it works fine. Sorry for the inconvenience.

**Comment by eneiluj** [comment]
Don't be sorry. Thanks a lot for the tests and feedback!
