### ISSUE TITLE
Show Association Dialog only if there are Simple Members

### ISSUE THREAD

**Issue by simonspa** [eneiluj/cospend-nc#8]
Currently in the settings the dialog for associating simple members with NC users is always shown, even if there are no simple project members. Furthermore, the drop down list for association shows all members, also NC users:

![image](https://user-images.githubusercontent.com/1677436/97672801-f4cfcc00-1a8a-11eb-940f-80a01202d6cd.png)

I would suggest
* to only show this setting if there are actually simple members present in the project
* to filter the list of selectable users in the dropdown to simple project members

This would clarify the functionality a bit more I would say.

**Comment by eneiluj** [comment]
Well there is still the use case where you want to change the user associated with a member. I think the confusion only comes from the label saying "associate a **simple** member". What do you think about changing it to " Associate a member with a Nextcloud user"?

**Comment by simonspa** [comment]
Sounds good to me!
