### ISSUE TITLE
make cospend responsive

### ISSUE THREAD

**Issue by siccovansas** [eneiluj/cospend-nc#82]
If you open a cospend project on a small (smartphone) screen you see that the page is too wide. You need to scroll horizontally to view all parts of the page.

It would be awesome if cospend is responsive so it is easier to use on small screens/smartphones.

Thanks for the great app 🎉!

![Screenshot_20210910-154132_Firefox](https://user-images.githubusercontent.com/696839/132862583-f091d882-9f30-4bdd-bc43-adf431d8cb65.jpg)

**Comment by eneiluj** [comment]
Thanks for the bug report.
I didn't put a lot of effort in that area because there always has been MoneyBuster, the associated Android app. But you're right, much better if it's responsive. It's now done:
![aaa](https://user-images.githubusercontent.com/11291457/133003478-9716759b-fb60-44f1-99db-265ee81b1ada.png)

it's available in latest nightly (`v1.3.16-7-nightly`). It would be awesome if you could try it. Tell me if want to do so and need help to install the nightly. I would recommend to install it on a test instance as it's full of new stuff and only partially tested for the moment.

**Comment by siccovansas** [comment]
Great, thx! How can I install the nightly? I tried looking it up (also for other apps), but couldn't find it.

**Comment by eneiluj** [comment]
https://github.com/eneiluj/cospend-nc#nightly

**Comment by eneiluj** [comment]
v1.3.18 is out. No need to install the nightly anymore. Still very interested in your tests :grin:.

**Comment by siccovansas** [comment]
Thanks for adding the documentation on how to install the nightly! I wasn't able to test it before you released v1.3.18 :). I installed v1.3.18 and the new 'New bill' screens is now perfectly responsive 🎉! Thanks!

**Comment by eneiluj** [comment]
Thanks for the feedback and the enthusiasm!

**Comment by ndx1905-github** [comment]
That's a great add, I agree.
I have an iphone so no moneybuster for me, and payforme is still in a too early development to be really useful at this point

The responsive UI does not yield the same result for me... and it looks less usable. Can you please have a look ?

thanks
![IMG_7FD45AEC731F-1](https://user-images.githubusercontent.com/64833823/134959331-dee904a8-a5f2-4bda-814f-54e380b2ca20.jpeg)
s!

**Comment by ndx1905-github** [comment]
That's a great add, I agree.
I have an iphone so no moneybuster for me, and payforme is still in a too early development to be really useful at this point

The responsive UI does not yield the same result for me... and it looks less usable. Can you please have a look ?

than
![IMG_7FD45AEC731F-1](https://user-images.githubusercontent.com/64833823/134959699-b97a482f-b815-4322-b702-3b91e7261ae3.png)
ks

**Comment by eneiluj** [comment]
It looks quite usable in your screenshot :grin: Is it worse than before? How?

As it's impossible to emulate an apple device and i don't have any around me it's hard to make some test in those platforms. Could you try with Firefox on iOS?

**Comment by ndx1905-github** [comment]
Thanks for the reply!

You’re right it’s usable but all the boxes are truncated on the right side. Thought it might be a css issue but I really don’t know. 

On iOS all web browsers use the safari rendering engine, even Firefox and chrome. Here is a Firefox screenshot as asked though : 

![Capture d’écran   2021-09-28 à 09 53 02](https://user-images.githubusercontent.com/64833823/135046841-731bff25-6b6e-4af4-a817-7c9c2d1f35d8.png)
