### ISSUE TITLE
Cospend prevent to download photo on mobile

### ISSUE THREAD

**Issue by Thovi98** [eneiluj/cospend-nc#83]
Hello,

Thanks for Cospend which is an awesome app !

I’ve got a strange issue recently : I made some photos, and I can (and everybody who has the link) download them from a desktop browser.
But when on mobile, downloading a photo leads to "an internal error" page. 

Looking to the logs, I come accross this : 

`{"reqId":"c3W0Rc3C0FYEiqbgk677","level":3,"time":"2021-09-13T15:55:36+00:00","remoteAddr":"91.179.111.180","user":"--","app":"index","method":"GET","url":"/s/CzRBXoM7CGMHwyw/download?path=%2F&files=DSC_0001.JPG&downloadStartSecret=wa8i3olbiah","message":"Argument 1 passed to OCA\\Cospend\\Service\\ProjectService::getProjectNames() must be of the type string, null given, called in /var/www/nextcloud/apps/cospend/lib/Activity/CospendProvider.php on line 84","userAgent":"Mozilla/5.0 (Linux; Android 11; M2101K7AG Build/RKQ1.201022.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/93.0.4577.62 Mobile Safari/537.36 [FB_IAB/Orca-Android;FBAV/329.0.0.12.118;]","version":"22.1.1.2","exception":{"Exception":"Exception","Message":"Argument 1 passed to OCA\\Cospend\\Service\\ProjectService::getProjectNames() must be of the type string, null given, called in /var/www/nextcloud/apps/cospend/lib/Activity/CospendProvider.php on line 84","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareController"},"downloadShare"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_Sharing\\Controller\\ShareController","downloadShare",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"filename":"","token":"CzRBXoM7CGMHwyw","_route":"files_sharing.Share.downloadShare"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/s/CzRBXoM7CGMHwyw/download"]},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"TypeError","Message":"Argument 1 passed to OCA\\Cospend\\Service\\ProjectService::getProjectNames() must be of the type string, null given, called in /var/www/nextcloud/apps/cospend/lib/Activity/CospendProvider.php on line 84","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/cospend/lib/Activity/CospendProvider.php","line":84,"function":"getProjectNames","class":"OCA\\Cospend\\Service\\ProjectService","type":"->","args":[null]},{"function":"__construct","class":"OCA\\Cospend\\Activity\\CospendProvider","type":"->","args":[{"__class__":"OC\\URLGenerator"},{"__class__":"OCA\\Cospend\\Activity\\ActivityManager"},{"__class__":"OC\\User\\Manager"},{"__class__":"OC\\Group\\Manager"},{"__class__":"OC\\App\\AppManager"},{"__class__":"OC\\L10N\\LazyL10N"},{"__class__":"OC\\AllConfig"},{"__class__":"OCA\\Cospend\\Service\\ProjectService"},null]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"newInstanceArgs","class":"ReflectionClass","type":"->","args":[[{"__class__":"OC\\URLGenerator"},{"__class__":"OCA\\Cospend\\Activity\\ActivityManager"},{"__class__":"OC\\User\\Manager"},{"__class__":"OC\\Group\\Manager"},{"__class__":"OC\\App\\AppManager"},"And 4 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Cospend\\Activity\\CospendProvider","__class__":"ReflectionClass"}]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Cospend\\Activity\\CospendProvider"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":460,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Cospend\\Activity\\CospendProvider"]},{"file":"/var/www/nextcloud/lib/private/ServerContainer.php","line":145,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Cospend\\Activity\\CospendProvider"]},{"file":"/var/www/nextcloud/lib/private/Activity/Manager.php","line":245,"function":"query","class":"OC\\ServerContainer","type":"->","args":["OCA\\Cospend\\Activity\\CospendProvider"]},{"file":"/var/www/nextcloud/apps/activity/lib/NotificationGenerator.php","line":82,"function":"getProviders","class":"OC\\Activity\\Manager","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/activity/lib/NotificationGenerator.php","line":111,"function":"populateEvent","class":"OCA\\Activity\\NotificationGenerator","type":"->","args":[{"__class__":"OC\\Activity\\Event"},"fr"]},{"file":"/var/www/nextcloud/lib/private/Notification/Manager.php","line":333,"function":"prepare","class":"OCA\\Activity\\NotificationGenerator","type":"->","args":[{"__class__":"OC\\Notification\\Notification"},"fr"]},{"file":"/var/www/nextcloud/apps/notifications/lib/Push.php","line":192,"function":"prepare","class":"OC\\Notification\\Manager","type":"->","args":[{"__class__":"OC\\Notification\\Notification"},"fr"]},{"file":"/var/www/nextcloud/apps/notifications/lib/App.php","line":58,"function":"pushToDevice","class":"OCA\\Notifications\\Push","type":"->","args":[319,{"__class__":"OC\\Notification\\Notification"}]},{"file":"/var/www/nextcloud/lib/private/Notification/Manager.php","line":294,"function":"notify","class":"OCA\\Notifications\\App","type":"->","args":[{"__class__":"OC\\Notification\\Notification"}]},{"file":"/var/www/nextcloud/apps/activity/lib/NotificationGenerator.php","line":53,"function":"notify","class":"OC\\Notification\\Manager","type":"->","args":[{"__class__":"OC\\Notification\\Notification"}]},{"file":"/var/www/nextcloud/apps/activity/lib/Consumer.php","line":72,"function":"sendNotificationForEvent","class":"OCA\\Activity\\NotificationGenerator","type":"->","args":[{"__class__":"OC\\Activity\\Event"},398446]},{"file":"/var/www/nextcloud/lib/private/Activity/Manager.php","line":157,"function":"receive","class":"OCA\\Activity\\Consumer","type":"->","args":[{"__class__":"OC\\Activity\\Event"}]},{"file":"/var/www/nextcloud/apps/files_sharing/lib/Controller/ShareController.php","line":748,"function":"publish","class":"OC\\Activity\\Manager","type":"->","args":[{"__class__":"OC\\Activity\\Event"}]},{"file":"/var/www/nextcloud/apps/files_sharing/lib/Controller/ShareController.php","line":720,"function":"publishActivity","class":"OCA\\Files_Sharing\\Controller\\ShareController","type":"->","args":["public_shared_file_downloaded",["/Images/2021/Septembre - Stavelot/DSC_0001.JPG"],"thomas",2123286,"/Images/2021/Septembre - Stavelot/DSC_0001.JPG"]},{"file":"/var/www/nextcloud/apps/files_sharing/lib/Controller/ShareController.php","line":679,"function":"singleFileDownloaded","class":"OCA\\Files_Sharing\\Controller\\ShareController","type":"->","args":[{"__class__":"OC\\Share20\\Share"},{"__class__":"OC\\Files\\Node\\File"}]},{"file":"/var/www/nextcloud/apps/files_sharing/lib/Controller/ShareController.php","line":611,"function":"fileListDownloaded","class":"OCA\\Files_Sharing\\Controller\\ShareController","type":"->","args":[{"__class__":"OC\\Share20\\Share"},["DSC_0001.JPG"],{"__class__":"OC\\Files\\Node\\Folder"}]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"downloadShare","class":"OCA\\Files_Sharing\\Controller\\ShareController","type":"->","args":["CzRBXoM7CGMHwyw","DSC_0001.JPG","/","wa8i3olbiah"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareController"},"downloadShare"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareController"},"downloadShare"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_Sharing\\Controller\\ShareController","downloadShare",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"filename":"","token":"CzRBXoM7CGMHwyw","_route":"files_sharing.Share.downloadShare"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/s/CzRBXoM7CGMHwyw/download"]},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/cospend/lib/Service/ProjectService.php","Line":2391},"CustomMessage":"--"},"id":"613f7888a4ac8"}`

So I deactivated Cospend and now I can download my photos normally from a mobile browser.

It’s strange because those photos doesn’t have anything related to Cospend.

Thanks for your consideration :)

**Comment by eneiluj** [comment]
Hey, thanks for the bug report. This has already been fixed and will be included in next release. Could you try latest [nightly](https://github.com/eneiluj/cospend-nc/#nightly) (on a test instance) and confirm it's working fine? That would be awesome and speed up the release process :grin:.

**Comment by Thovi98** [comment]
I have no test instances. If it’s not a problem, I can try on my production instance, but I have not so much time right now...

**Comment by eneiluj** [comment]
Well I'm going to make the release today anyway. Just wait and upgrade as usual. I'm still interested to know if the issue has gone away :grin: with the new release.

And I wouldn't recommend to use nightly builds on productions instances because if the database changes are then reverted, it can mess with your database schema.

**Comment by eneiluj** [comment]
v1.3.17 is out, you should be able to upgrade soon.

**Comment by Thovi98** [comment]
Thank you for your support ! It works great now !!
You are an amazing developper 👏
