### ISSUE TITLE
Feature request: Move bills between projects

### ISSUE THREAD

**Issue by ManuelSailer** [eneiluj/cospend-nc#87]
I have an ongoing project to share costs of living with my partner. We add bills continuously and settle the project from time to time, add bills, settle the project, add bills, …
Now we have the situation that we had some expenses in the past (and added the bills to our ongoing project) and want to share these expenses later with other people (e. g. some friends who join a weekend trip and who we want to share the previously made expenses with).

My idea was to create a new project for that group of people and move the bills from our ongoing project to the new project. But I did not find a way to achieve this. There seems to be no “move bill to other project” functionality in the UI, so I tried to manually “fix” the projectid in the cospend_bills database table. This removed the bills from the old project but lead to an error message when loading the new project.

Is there any possibility to move bills between projects and if not, could this be an improvement for Cospend?

Would be great if anyone could help. And thanks for your time.

**Comment by amendogni** [comment]
I was looking for exactly the same feature!

I use Cospend in both single user and multiple user mode so it happens that the same bill appears on my personal budget and in the project with my partner. It would be great if it would be possible to duplicate the same bill on other project.  

Thanks for your time and I hope that this feature will be implemented

**Comment by ManuelSailer** [comment]
Implemented in #165.
Works like a charm.
Thank you very much @Almamu.
