### ISSUE TITLE
Ordering of members in the interface

### ISSUE THREAD

**Issue by valkalon** [eneiluj/cospend-nc#89]
Hi, 
I'm a huge fan of cospend, thanks a lot for the tool!
When I create members on the left side of the screen they are ordered alphabetically
but on the right side they are ordered by creation time.

![Selection_1157](https://user-images.githubusercontent.com/7339264/135747591-b018d0e2-eaf6-4a27-be49-f5ca17ed987d.jpg)

Any chance to make it alphabetical everywhere this way we can have some control
on the order of display please?

**Comment by eneiluj** [comment]
Thanks for the bug report. It's now fixed and this will be included in the next release. It is also available in `v1.4.0-1-nightly` if you want to try it out.

By the way, member order criteria can be changed in the settings (left navigation bar).

**Comment by eneiluj** [comment]
Feel free to reopen later if it does not work properly.

**Comment by valkalon** [comment]
eneiluj, thanks for the quick reaction and the info for member order criteria.
